Stratio/sparta

doc/src/site/sphinx/inputs.rst
KafkaDirectInput is missing from docs but is supported. Add this input doc.
=> Add KafkaDirectInput to inputs docs

driver/src/test/scala/com/stratio/sparkta/driver/test/factory/CuratorFactoryHolderIT.scala
Due to a typo in the configuration, CuratoryFactoryHolderIT was failing.
=> Typo in configuration of CuratorFactoryHolderIT

plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala
Tables were always updated to values of last dataframe data
=> Cassandra tables were overriden. Close #233

doc/src/site/sphinx/outputs.rst, driver/src/main/scala/com/stratio/sparkta/driver/service/StreamingContextService.scala, examples/policies/ITwitter-OParquet.json, plugins/bucketer-dateTime/pom.xml, plugins/output-parquet/pom.xml, plugins/output-parquet/src/main/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutput.scala, plugins/output-parquet/src/test/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutputSpec.scala, plugins/parser-datetime/pom.xml, plugins/pom.xml, pom.xml, sdk/pom.xml, sdk/src/main/scala/com/stratio/sparkta/sdk/DateOperations.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/DateOperationsSpec.scala
Output for parquet files. It closes issue #75. We need an extra parameter ```path``` and optional one ```datePattern``` if you want path formatting. I changed joda-time by NScala-time (Scala wrapper). Also I changed a tailrec function to improve readability. Added methods to DateOperations to calculate paths with patterns and granularity.
@arinconstrio 
Added 7 test. All passed
=> Parquet output, issue #75

driver/src/test/resources/policies/IKafka-OPrint.json, driver/src/test/scala/com/stratio/sparkta/driver/test/service/StreamingContextServiceIT.scala
Test fixed. Assign sparkta home depending if its run in mvn or in the IDE
=> Fix jenkins build

aggregator/src/main/scala/com/stratio/sparkta/aggregator/DataCube.scala
Right now Datetime fields are stored with Long values and must be stored as Date objects
=> Timestamp must be a Date object

test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOElasticsearchAT.scala
Wrong name in the fixture path causes that the ISocketOElasticsearch.json fails.
@anistal 
1 text fixed.
=> wrong name in the fixture path

test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOParquetAT.scala
Tests are failing because they are checking that a Seq is the same that another Seq. The order of the elements could not be the same then the right data structure to use is a Map.
@sgomezg 
1 acceptance test added. All passed
=> A test fails because is comparing Seqs intead fo Sets

pom.xml, run_before_push.sh
Added scoverage plugin. It closes #304
Currently you can exec run_before_push.sh to do all stuff or, if you prefer, create a [git hook](https://gist.github.com/sgomezg/94c87a9f282be9d914b6)
SCoverage will create a file like [PROJECT]/target/site/scoverage/index.html
@anistal 
37,79 %. No changes
=> Coverage plugin

README.md
Simple fix in the images of the readme file:
- Using relative paths.
- Correct alt text.
=> Fixing paths to images in the readme file.

dist/pom.xml, serving-api/src/main/scala/com/stratio/sparkta/serving/api/constants/AppConstant.scala
fixes 
run script pointed to a wrong class
we were trying to get jars from an non existing folder named driver at SPARKTA_HOME
@danielcsant 
All  passed
=> fix run script & remove driver from relative path to find jars

driver/src/main/scala/com/stratio/sparkta/driver/models/AggregationPoliciesModel.scala, driver/src/main/scala/com/stratio/sparkta/driver/service/SparktaJob.scala, driver/src/test/scala/com/stratio/sparkta/driver/test/models/AggregationPoliciesSpec.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ClusterContextActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/PolicyHelper.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/route/PolicyRoutesSpec.scala
There is an error parsing policies when the input is in a fragment.
It closes #507 
@antonioalf    
One scenario added to PolicyHelperSpec.scala
=> fixed error related with only one input per policy

aggregator/pom.xml, driver/pom.xml, pom.xml
Spark upgrade to 1.4.1. It closes #446
@danielcsant 
No changes
No changes
No info
=> Spark upgrade to 1.4.1

plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala, plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/dao/MongoDbDAO.scala
Now all the MongoDB fields of the policy are strings
All passed
No changes
No info
=> Refactor of MongoDB output

plugins/output-redis/src/main/scala/com/stratio/sparkta/plugin/output/redis/RedisOutput.scala, plugins/output-redis/src/main/scala/com/stratio/sparkta/plugin/output/redis/dao/AbstractRedisDAO.scala, test-at/src/test/resources/policies/ISocket-ORedis-operators.json
Redis fields are Strings in the policy now
All passed
No changes
No info
=> Refactor of Redis output

serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/AggregationPoliciesModel.scala
Before, If we didn't specify the name, the policyContext was created with a default name. Now, the name is mandatory.
=> Remove default name

serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActor.scala
Added mandatory fields with the annotation called required
Now, the endpoint returns the status of the policy. Now, the response is like this:
```javascript
[
{
"status": "Failed",
"policy": {
"id": "id",
"storageLevel": "MEMORY_AND_DISK_SER_1",
....
},
},
...
{
"status": "NotStarted",
"policy": {
"id": "id2",
"storageLevel": "MEMORY_AND_DISK_SER_2",
....
}
}
]
```
If the policy doesn't have status, NotStarted will be shown.
All passed.
No changes
No info
=> Added status to response in findAll method

serving-api/src/main/resources/policy_schema.json, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/PolicyHelper.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/AggregationPoliciesModel.scala
Added all types and rules for the policy validation in json level.
Now validate in the update process too.
The returned json value has been changed with the fillFragments process.
It close #924 #939 and #834 
All passed.
No changes
No info
=> Policies validation and returned values with fragments

web/src/data-templates/input.json
Since the Twitter input parses the event it is not usable from front.
But it will be still usable from command line
All passed. Tested the new functions.
No changes
No info
=> Removed Twitter input from template

examples/scripts/loadExampleConfiguration_Cassandra.sh, examples/scripts/loadExampleConfiguration_Elasticsearch.sh, examples/scripts/loadExampleConfiguration_Mongo.sh
Currently, manager is running all scripts (provided all persistances are installed) which creates issues with the input fragment creation. Each script tries to create the input fragment again, creating havoc when trying to create the policy.
A new check has been added to verify whether the fragment already exists or not. If it doesn't exist, we create it, and if it exists, we use the existing id.
=> fix initital configuration scripts

pom.xml
There where a test that was failing beacuse a plugin was not packaged yet. It is fixed packaging plugins at first
=> module reorder

doc/src/site/sphinx/outputs.rst, driver/src/main/scala/com/stratio/sparkta/driver/SparktaJob.scala, driver/src/test/scala/com/stratio/sparkta/driver/test/models/AggregationPoliciesSpec.scala, plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala, plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/dao/CassandraDAO.scala, plugins/output-cassandra/src/test/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraDaoSpec.scala, plugins/output-cassandra/src/test/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutputSpec.scala, plugins/output-csv/src/main/scala/com/stratio/sparkta/plugin/output/csv/CsvOutput.scala, plugins/output-csv/src/test/scala/com/stratio/sparkta/plugin/output/csv/CsvOutputSpec.scala, plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala, plugins/output-elasticsearch/src/test/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutputSpec.scala, plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala, plugins/output-parquet/src/main/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutput.scala, plugins/output-parquet/src/test/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutputIT.scala, plugins/output-print/src/main/scala/com/stratio/sparkta/plugin/output/print/PrintOutput.scala, plugins/output-redis/src/main/scala/com/stratio/sparkta/plugin/output/redis/RedisOutput.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/OutputSpec.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/test/OutputMock.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/service/http/HttpServiceBaseSpec.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/AggregationPoliciesModel.scala, serving-core/src/test/scala/com/stratio/sparkta/serving/core/helpers/PolicyHelperSpec.scala, serving-core/src/test/scala/com/stratio/sparkta/serving/core/models/test/AggregationPolicySpec.scala, test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOCassandraOperatorsIT.scala, web/src/data-templates/output.json
Now all the policies are versioned in Zookeeper. When the user modify one cube that contains the policy we increment the version number.
Cassandra output are refactored, now use the policy version for the names of the tables associated to one cube.
@sgomezg  @anistal @arinconstrio
=> Policies auto-versioned in Zookeeper for Outputs tables names

plugins/field-dateTime/src/main/scala/com/stratio/sparkta/plugin/field/datetime/DateTimeField.scala, plugins/field-dateTime/src/test/scala/com/stratio/sparkta/plugin/field/datetime/test/DateTimeFieldSpec.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/TypeOp.scala
SPARKTA-1201. Now we can accept long types because we can convert to the correct Date type with the typeConversions trait.
@sgomezg  @anistal 
Added more cases in the test.
Removed scala style problem.
=> DateTimefield type accept long types

driver/src/main/scala/com/stratio/sparkta/driver/SparktaJob.scala, plugins/input-kafka/src/main/scala/com/stratio/sparkta/plugin/input/kafka/KafkaDirectInput.scala, plugins/input-kafka/src/main/scala/com/stratio/sparkta/plugin/input/kafka/KafkaInput.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
* SPARKTA-174
* Discard the empty dstream must be in the output in the foreachRDD, if we make this condition in SparktaJob with the size of the object in the JVM or make a DStream extended with the functionality, the streaming run only in this way because is the fist action.
* Refactor Kafka input for scalastyle..
@Gschiavon
=> Discarding empty DStream

driver/src/test/scala/com/stratio/sparkta/driver/test/factory/SchemaFactoryTest.scala, plugins/field-default/src/test/scala/com/stratio/sparkta/plugin/field/default/DefaultFieldTest.scala, plugins/operator-avg/src/main/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperator.scala, plugins/operator-count/src/main/scala/com/stratio/sparkta/plugin/operator/count/CountOperator.scala, plugins/operator-count/src/test/scala/com.stratio.sparkta.plugin.operator.count/CountOperatorTest.scala, plugins/operator-entityCount/src/test/scala/com/stratio/sparkta/plugin/operator/entityCount/EntityCountOperatorTest.scala, plugins/operator-max/src/main/scala/com/stratio/sparkta/plugin/operator/max/MaxOperator.scala, plugins/operator-median/src/main/scala/com/stratio/sparkta/plugin/operator/median/MedianOperator.scala, plugins/operator-min/src/main/scala/com/stratio/sparkta/plugin/operator/min/MinOperator.scala, plugins/operator-range/src/main/scala/com/stratio/sparkta/plugin/operator/range/RangeOperator.scala, plugins/operator-stddev/src/main/scala/com/stratio/sparkta/plugin/operator/stddev/StddevOperator.scala, plugins/operator-sum/src/main/scala/com/stratio/sparkta/plugin/operator/sum/SumOperator.scala, plugins/operator-variance/src/main/scala/com/stratio/sparkta/plugin/operator/variance/VarianceOperator.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/FilterModel.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/Operator.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/TypeOp.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/OperatorTest.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/test/OperatorMock.scala
* Now in the filters we can select the type of the field value. If you not select anything sparkta use the default in the operator.
* Bug in TypeOperation are corrected, added more types conversions.
@anistal
=> Field types in Operator filters

dist/src/main/unix/etc/init.d/sparkta
Solved issue related to PID folder creation. When we restart the server, folder /var/run/sds is deleted. Now we are creating it again. SPARKTA-235
@Gschiavon , @gserranojc   
All passed.
No changes
No info
=> Solved issue related to PID folder creation

plugins/parser-ingestion/pom.xml, plugins/parser-ingestion/src/main/scala/com/stratio/sparkta/plugin/parser/ingestion/IngestionParser.scala, plugins/parser-ingestion/src/test/resources/log4j.xml, plugins/parser-ingestion/src/test/scala/com/stratio/sparkta/plugin/parser/ingestion/IngestionParserTest.scala, plugins/pom.xml, serving-core/src/main/scala/com/stratio/sparkta/serving/core/constants/AppConstant.scala
This new parser is used to compute events generated by Stratio Ingestion.
Stratio Ingestion sends a JSON with a field "columns" that contains a list of elements that Sparkta will be use to extract dimensions.
Example:
{
"columns": [
{
"column": "ColumnA",
"value": "ColumnAValue"
}
]
}
The main idea is to have an schema in the Ingestion Parser's configuration to build the event.
Example:
"configuration": {
"ColumnA": "string"
}
Created 1 test with a 100% of coverage over the IngestionParser.
=> [SPARKTA-109] New parser used in Stratio Ingestion

dist/src/main/resources/application.conf, serving-api/src/main/resources/reference.conf
This property should have the following value for taking the cores depending on the machine:
spark.master = "local[*]"
@anistal 
All passed.
No changes
No info
=> SPARKTA-263 Default application.conf values are wrong

aggregator/src/main/scala/com/stratio/sparkta/aggregator/Cube.scala, aggregator/src/main/scala/com/stratio/sparkta/aggregator/CubeMaker.scala, aggregator/src/test/scala/com/stratio/sparkta/aggregator/CubeMakerTest.scala, aggregator/src/test/scala/com/stratio/sparkta/aggregator/CubeTest.scala, driver/src/main/scala/com/stratio/sparkta/driver/SparktaJob.scala, driver/src/main/scala/com/stratio/sparkta/driver/factory/SchemaFactory.scala, driver/src/main/scala/com/stratio/sparkta/driver/util/ReflectionUtils.scala, driver/src/test/scala/com/stratio/sparkta/driver/test/factory/SchemaFactoryTest.scala, plugins/output-cassandra/src/test/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraDaoTest.scala, plugins/output-elasticsearch/src/test/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutputTest.scala, plugins/output-elasticsearch/src/test/scala/com/stratio/sparkta/plugin/output/elasticsearch/dao/ElasticSearchDaoTest.scala, plugins/output-parquet/src/main/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutput.scala, plugins/output-solr/src/main/scala/com/stratio/sparkta/plugin/output/solr/SolrDAO.scala, plugins/output-solr/src/main/scala/com/stratio/sparkta/plugin/output/solr/SolrOutput.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/AggregateOperations.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/DimensionValuesTime.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/TableSchema.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/AggregateOperationsTest.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/OutputTest.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/TableSchemaTest.scala, test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOCassandraOperatorsIT.scala, test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOCsvOperatorsIT.scala, test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOElasticsearchOperatorsIT.scala, test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOMongoFiltersJsonIT.scala, test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOMongoOperatorsIT.scala
Table names from cube. SPARKTA-184
@gserranojc    
All OK
No changes
No info
=> Table names from cube. SPARKTA-184

examples/policies/ITwitterJson-OCassandra.json, examples/policies/fragments/CassandraFragment.json, test-at/src/test/resources/policies/ISocket-OCassandra-operators.json, test-at/src/test/resources/policies/ISocket-OCassandra.json, web/src/data-templates/output.json
Setting the value for this property to 2 seconds. By default it is in 250 milliseconds which makes the output create a new Cassandra connection in every DStream.
This PR will allow the Cassandra output to reuse a connection.
=> SPARKTA-217 [WEB] Set default property value to Cassandra output

plugins/field-dateTime/src/main/scala/com/stratio/sparkta/plugin/field/datetime/DateTimeField.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/AggregationTime.scala, sdk/src/main/scala/com/stratio/sparkta/sdk/DateOperations.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/DateOperationsTest.scala, sdk/src/test/scala/com/stratio/sparkta/sdk/test/AggregationTimeTest.scala
Custom granularity to aggregate data added.
Now Sparkta is able to aggregate by any time, you can customize it with the followings unit of time:
- Seconds e.g 15s, 20s, etc
- Minutes e.g 15m, 20m, etc
- Hours e.g 15h, 20h, etc
- Days e.g 15d, 20d, etc
And also you can still aggregating the data like before.
Examples:
- By minute
```
"cubes": [
{
"name": "testCube",
"checkpointConfig": {
"timeDimension": "minute",
"granularity": "minute",
"interval": 30000,
"timeAvailability": 60000
}
```
- By 15 seconds
```
"cubes": [
{
"name": "testCube",
"checkpointConfig": {
"timeDimension": "minute",
"granularity": "15s",
"interval": 30000,
"timeAvailability": 60000
}
```
- By 30 minutes
```
"cubes": [
{
"name": "testCube",
"checkpointConfig": {
"timeDimension": "minute",
"granularity": "30m", …
```
=> SPARKTA-285 Generic way to define the granularity

serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ControllerActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SwaggerActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/TemplateActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/handler/CustomExceptionHandler.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/AppStatusHttpService.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyContextHttpService.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/actor/FragmentActorTest.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/actor/TemplateActorTest.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/service/http/PolicyContextHttpServiceTest.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/actor/FragmentActor.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/helpers/PolicyHelper.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/ErrorModel.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/FragmentElementModel.scala, serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/PolicyElementModel.scala, testsAT/src/test/java/com/stratio/sparta/testsAT/automated/gui/policies/AddAutoFragmentCreation.java, testsAT/src/test/resources/features/automated/api/policyContexts/getPolicyContexts.feature, testsAT/src/test/resources/features/automated/api/policyContexts/postPolicyContexts.feature, testsAT/src/test/resources/features/automated/api/policyContexts/putPolicyContexts.feature, testsAT/src/test/resources/features/automated/gui/policies/addAutoFragmentCreation.feature
The idea is to extract input and outputs out of the policy and parse them into fragments so the policy, inputs and outputs could be shown in the user interface.
**Given** an user using Sparkta with the command line
**When** posts a policy thought policyContext endpoint with a standard policy (see attached file)
**Then** input, outputs and policy should be shown in the user interface
**Given** an user using Sparkta with the command line
**When** posts a new policy using policyContext endpoint with a standard policy which contains existing input/outputs (**exactly equals as existing ones: same name, type and property map**)
**Then** existing input/outputs should be shown in the user interface and policy will start. No error will be thrown and already existing input/outputs will be reused. …
=> SPARKTA-198 add input/outputs when a policy is submitted

serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ControllerActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SwaggerActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/TemplateActor.scala
Removed implicit handler from some classes in order to use expected CustomExceptionHandler.
=> SPARKTA-393 fix CustomExceptionHandler behaviour

serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpServiceTest.scala, serving-core/pom.xml, serving-core/src/main/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActor.scala, serving-core/src/test/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActorTest.scala, testsAT/src/test/resources/features/automated/api/policies/deletePolicies.feature, testsAT/src/test/resources/features/automated/gui/policies/deletePolicy.feature
Delete policy context when deleting an existing policy
**Given** an existing policy
**when** trying to delete this policy
**then** this policy and its context must be deleted
**Given** an unexisting policy
**when** trying to delete this policy
**then** an exception will be thrown and 500 status error will the returned
=> [SPARTA-410] delete policy context when deleting policy

plugins/parser-geo/.gitignore, plugins/parser-geo/pom.xml, plugins/parser-geo/src/main/scala/com/stratio/sparkta/plugin/parser/geo/GeoParser.scala, plugins/parser-geo/src/test/resources/log4j.xml, plugins/parser-geo/src/test/scala/com/stratio/sparkta/plugin/test/parser/geo/GeoParserTest.scala, plugins/pom.xml, pom.xml, serving-core/src/main/scala/com/stratio/sparkta/serving/core/constants/AppConstant.scala
Added a new parser in order to join latitude and longitude in only one field.
The parser should be something like this:
```javascript
{
"name": "geo-parser",
"order": 1,
"inputField": "",
"outputFields": [
"geo"
],
"type": "Geo",
"configuration": {
"latitude": "lat",
"latitude": "long"
}
}
```
In the configuration object you can identify the names of the latitude field and longitude field. By default, these names are *latitude* and *longitude*
Ticket in Jira -> [SPARKTA-433](https://stratio.atlassian.net/browse/SPARKTA-433)
=> SPARKTA-433 Added new parser for geolocation

serving-api/pom.xml
Plugins were as provided scope so Reflection cannot load them
=> [SPARKTA-459] Plugins in dev environment

serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyContextHttpService.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/utils/PolicyStatusUtils.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/utils/PolicyUtils.scala, serving-api/src/main/scala/com/stratio/sparkta/serving/api/utils/SparkStreamingContextUtils.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelperTest.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/utils/BaseUtilsTest.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/utils/PolicyStatusUtilsTest.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/utils/PolicyUtilsTest.scala, serving-api/src/test/scala/com/stratio/sparkta/serving/api/utils/SparkStreamingContextUtilsTest.scala
Check when Sparta runs in **local/standalone** mode and avoid multiple policies run at the same time.
***given*** an instance of Sparta (local/standalone mode) with a started policy
***when*** you try to run other policy
***then*** return an error
***given*** an instance of Sparta (local/standalone mode) with a started policy named "A"
***when*** you try to commit a new policy named "B"
***then*** the new policy will be created but not launched
***given*** an instance of Sparta (cluster mode) with a started policy named "A"
***when*** you try to run other policy "B"
***then*** start policy "B" at the same time as "A"
=> [SPARKTA-388] fix running policies number on local mode

web/pom.xml
When you try to package the project from anywhere outside Stratio, the web module compilation fails because there are some explicit dependencies to Stratio Maven repositories.
In order to check the correct behaviour, you have to delete web/node and web/node_modules directories and try to compile web module using both new "node" maven profile and default profile. Verify your build finishes successfully.
=> [SPARKTA-470] resolve node dependencies downloading from outside Stratio

dist/pom.xml, dist/src/main/unix/files_and_dirs/etc/default/sparta-variables
Given a Sparta installation
When the user change the JVM values at `/etc/default/sparta-variables` and restart sparta
Then these values should take effect
=> [SPARKTA-501] JVM arguments

dist/pom.xml
Minor change to add /var as a path to exclude in dist pom.xml
=> [SPARKTA-522] Exclude /var in pom.xml

web/src/data-templates/policy.json, web/test/mock/policyTemplate.json
Add a default configuration to operators as in previous version:
{ "inputField": "field1" }
=> [SPARKTA-514][WEB]: Add a default configuration to operators

web/pom.xml
this way we prevent web tests from running during unit and integration tests, saving time in jenkins and reducing the chance to produce an error
=> avoid web tests to be run twice

dist/src/main/unix/files_and_dirs/bin/sparta.sh
**Given** an installation of Sparta
**When** throws unchecked errors
**Then** they should be shown at `/var/log/sds/sparta/sparta.log`
=> [SPARTA-528] Unchecked errors not shown

Docker/docker-entrypoint.sh, dist/src/main/resources/application.conf, serving-api/src/main/resources/reference.conf, serving-api/src/main/scala/com/stratio/sparta/serving/api/Sparta.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/helpers/SpartaHelper.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/ssl/SSLSupport.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/SpartaConfig.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/constants/AppConstant.scala
As an user I want to configure a certificate in my configuration as follows:
```
spray.can {
server {
server-header = "sparta api"
ssl-encryption = "on"
ssl-tracing = "on"
verbose-error-messages = "on"
}
}
sparta {
api {
host = localhost
port = 9090
certificate-file = "/home/user/certificates/stratio.jks"
certificate-password = "certificate password"
}
......
```
Then sparta has ssl support: https://localhost:9090 and all requests are securized.
To generate a valid certification:
```
keytool -genkey -keyalg RSA -alias stratio -keystore stratio.jks -storepass stratio -validity 360 -keysize 2048
```
=> [SPARKTA-361] Sparta with SSL

plugins/src/main/scala/com/stratio/sparta/plugin/output/kafka/producer/KafkaProducer.scala, plugins/src/test/scala/com/stratio/sparta/plugin/output/kafka/KafkaProducerTest.scala, web/src/data-templates/output.json, web/src/languages/en-US.json
**GIVEN** a running Sparta instance
**WHEN** you create a kafka output
**THEN** you can set the property "requiered ACKs" (before known as "Specify whether kafka producer waits for an acknowledgement from the broker (1), or not (0)") using checkbox (true/false) values instead of 0/1 values.
The documentation is already updated. Please check https://stratio.atlassian.net/wiki/display/SPARKTA/7.4+Outputs#id-7.4Outputs-8.4.9Kafka
=> [SPARTA-530] field name too much descriptive

testsAT/src/test/resources/features/automated/endtoend/iSocketoCSV.feature, testsAT/src/test/resources/features/automated/endtoend/iSocketoCassandra.feature, testsAT/src/test/resources/features/automated/endtoend/iSocketoElasticsearch.feature, testsAT/src/test/resources/features/automated/endtoend/iSocketoMongoDB.feature
fix testsAT to use policyContext endpoint instead of policy to create policies, to make use of auto fragments generation and automatic startup of policy
=> fix testsAT to use policyContext endpoint instead of policy to create policies

Docker/docker-entrypoint.sh, dist/src/main/resources/application.conf, pom.xml, serving-api/pom.xml, serving-api/src/main/resources/reference.conf, serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/ControllerActor.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/SwaggerActor.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/headers/CacheSupport.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/headers/CorsSupport.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/AppStatusHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/BaseHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/FragmentHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyContextHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/TemplateHttpService.scala, serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/PolicyContextHttpServiceTest.scala, serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/TemplateHttpServiceTest.scala, test-at/src/test/scala/com/stratio/sparta/testat/SpartaATSuite.scala, web/src/scripts/controllers/policies.js, web/src/scripts/factories/request-interceptor-factory.js, web/test/factories/request-interceptor-factory.js
With this feature you can configure a SSO server. For this purpose you need to follow these steps:
- Add in your /etc/hosts: 
```
10.200.0.56 gosec01.dev.stratio.com
127.0.0.1 anistal
```
- Download the certification from: https://gosec01.dev.stratio.com:9005/cas/login (export Gosec's SSL certification with chrome/firefox/etc.)
- Create cacerts file: 
```
keytool -import -alias ca -file Stratio\ Inc\ CA -keystore cacerts -storepass stratio
```
- Run sparta with this option -Djavax.net.ssl.trustStore=/path/to/cacerts
- Configure your application.conf with oauth configuration:
```
oauth2 {
enable = "true"
url {
authorize = "https://gosec01.dev.stratio.com:9005/cas/oauth2.0/authorize"
accessToken = "https://gosec01.dev.stratio.com:9005/cas/oauth2.0/accessToken"
profile = …
```
=> [SPARTA-360] [SPARTA-510] Integration with GoSec

dist/src/main/resources/application.conf, serving-api/src/main/resources/reference.conf
**Given** a Sparta operating instance
**When** I set properties in order to run Sparta in standalone mode
**Then** Sparta should run and you could start any policy successfully
**NOTE**: some properties within reference.conf have been updated and/or remove.
=> [SPARTA-483] submiting policies to a Spark Standalone cluster

CHANGELOG.md, dist/pom.xml, dist/src/main/unix/scripts/postinst
When installing sparta the files should have these permissions:
root:stratio (775):
/etc/sds
/opt/sds
/var/log/sds
/var/sds
/var/run/sds
sparta:stratio (755):
/etc/sds/sparta
/var/log/sds/sparta
/opt/sds/sparta
root:root (644):
/etc/default/sparta-functions
/etc/default/sparta-variables
=> [SPARTA-576] Sparta package change share folder permissions

serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/PolicyActor.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/utils/PolicyUtils.scala
**GIVEN** a Sparta instance
**WHEN** you run a policy, wait for checkpoint folder to be created at localhost, stop de policy and finally delete the policy
**THEN** the checkpoint folder should be removed from localhost path
**GIVEN** a Sparta instance
**WHEN** you run a policy, wait for checkpoint folder to be created at HDFS, stop de policy and finally delete the policy
**THEN** the checkpoint folder should be removed from HDFS path
=> [SPARTA-467] when a policy is deleted, it's checkpoint folder must be removed

driver/src/main/scala/com/stratio/sparta/driver/util/HdfsUtils.scala
**Given** a Sparta instance using yarn mode
**When** you start a policy
**Then** the policy should run successfully, connect to HDFS and write within /user/stratio/sparta/<policy-id> with no errors
=> [SPARTA-592] add yarn-site.xml as hadoop resource

serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyHttpService.scala, web/src/scripts/controllers/policy-list.js, web/src/scripts/factories/policy-factory.js, web/src/scripts/services/api/api-policy-service.js, web/src/stratio-ui/template/components/ui.stratio.menuElement.html, web/src/views/policies.html, web/test/API/policy-service.js, web/test/controllers/policies-controller.js, web/test/policies/wizard/factory/policy-factory.js
**GIVEN** an existing policy within Sparta
**WHEN** you download this policy using user interface
**THEN** the downloaded file must contain an empty fragments field
**GIVEN** a running Sparta instance
**WHEN** you post a previously downloaded policy (removing id and changing name fields)
**THEN** the policy should start successfully
=> [SPARTA-599] Downloading the policy from the UI fragments are included

examples/policies/fragments/CassandraFragment.json, examples/policies/fragments/ElasticSearchFragment.json, examples/policies/fragments/MongoFragment.json, examples/policies/fragments/WebSocketFragment.json, examples/scripts/loadExampleConfiguration_Cassandra.sh, examples/scripts/loadExampleConfiguration_Elasticsearch.sh, examples/scripts/loadExampleConfiguration_Mongo.sh
**Given** a Sparta installation with no inputs, outputs or policies
**When** run the 3 scripts located at /opt/sds/sparta/examples/scripts
**Then** it should register 1 input, 3 outputs and 3 policies
=> SPARTA-617 Example scripts do not work properly due to an incorrect syntax

driver/src/main/scala/com/stratio/sparta/driver/SpartaJob.scala, project/scalastyle_config.xml
**Given** a policy with a KafkaDirect input
**When** Kafka service is not up
**Then** it should throw an exception giving the croncrete cause
**Given** a policy with a KafkaDirect input
**When** Kafka service is not up
**Then** it should **not** give following trace:
> LocalSparkStreamingContextActor:63 - null
> scala.MatchError: null ....
Fixed also scalastyle. Headers were giving errors
=> SPARTA-623 Error trace is not giving enought information

driver/src/main/scala/com/stratio/sparta/driver/SpartaClusterJob.scala, driver/src/test/scala/com/stratio/sparta/driver/test/cube/CubeTest.scala, plugins/src/test/scala/com/stratio/sparta/plugin/field/datetime/DateTimeFieldTest.scala, sdk/src/main/scala/com/stratio/sparta/sdk/TimeConfig.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/PolicyActor.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/constants/ActorsConstant.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/FragmentHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyContextHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyHttpService.scala, serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/FragmentHttpServiceTest.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/CuratorFactoryHolder.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/actor/FragmentActor.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/helpers/JarsHelper.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/helpers/OperationsHelper.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/helpers/PolicyHelper.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/helpers/ResourceManagerLink.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/models/PolicyElementModel.scala, serving-core/src/test/scala/com/stratio/sparta/serving/core/helpers/OperationsHelperTest.scala, test-at/src/test/scala/com/stratio/sparta/testat/internal/ISocketOElasticsearchJsonAT.scala, test-at/src/test/scala/com/stratio/sparta/testat/outputs/ISocketOElasticsearchOperatorsIT.scala
Due to update one input or output in Sparta UI it is neccesary update and modify the related policies
**Given** one updated input or output
**When** the sparta server receive the updated fragment
**Then** the policies that include the updated fragment should be modified with the new data
=> [SPARTA-638] [SERVING-CORE] [SERVING-API] Update related policies when one fragment are modified

plugins/src/main/scala/com/stratio/sparta/plugin/input/kafka/KafkaBase.scala, plugins/src/main/scala/com/stratio/sparta/plugin/input/kafka/KafkaDirectInput.scala, plugins/src/main/scala/com/stratio/sparta/plugin/input/kafka/KafkaInput.scala, plugins/src/main/scala/com/stratio/sparta/plugin/output/kafka/producer/KafkaProducer.scala, plugins/src/test/scala/com/stratio/sparta/plugin/input/kafka/getZkConnectionConfTest.scala, plugins/src/test/scala/com/stratio/sparta/plugin/output/kafka/KafkaProducerTest.scala, web/src/data-templates/input.json, web/src/data-templates/output.json, web/src/languages/en-US.json
**As** a user
**I want** to change the default zookeeper path in Kafka input and output
**So I** can have Kafka persisting the offset in other folder than the default
**Given** a Kafka configured with a zookeeper offset path different from the default
**When** launching a policy with a Kafka input configured
**Then** the policy should aggregate events
**Given** a Kafka configured with a zookeeper offset path different from the default
**When** launching a policy with a Kafka Direct input configured
**Then** the policy should aggregate events
**Given** a Kafka configured with a zookeeper offset path different from the default
**When** launching a policy with a Kafka output configured
**Then** the policy should aggregate events
Doc updated: …
=> [SPARTA-645] Zookeeper offset path

serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/ControllerActor.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/models/dto/LoggedUser.scala, serving-core/src/test/scala/com/stratio/sparta/serving/core/models/LoggedUserTest.scala
If a _LoggedUser_ cannot be parsed well from JSON, instead of returning an _AnonymousUser_ return **None**.
If security is enabled but _LoggedUser_ is None we will return an _Unauthorized_ in the routes.
=> LoggedUser when security is enabled cannot be an AnonymousUser

dist/src/main/resources/reference.conf, docker/sparta-server-utils.sh, serving-api/src/main/resources/reference.conf, serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/ConfigActor.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/ControllerActor.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/helpers/SpartaHelper.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/ConfigHttpService.scala, serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/SwaggerService.scala, serving-api/src/test/resources/reference.conf, serving-api/src/test/scala/com/stratio/sparta/serving/api/actor/ControllerActorTest.scala, serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/ConfigHttpServiceTest.scala, serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/HttpServiceBaseTest.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/config/SpartaConfig.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/constants/AkkaConstant.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/constants/AppConstant.scala, serving-core/src/main/scala/com/stratio/sparta/serving/core/models/frontend/FrontendConfiguration.scala, serving-core/src/test/resources/reference.conf
To create the /config endpoint, the following things have been added:
* service ConfigHttpService (and related Test class)
* actor ConfigActor
* FRONTEND_TIMEOUT environment variable
* sparta.config.frontend.timeout option in reference.conf
=> [SPARTA-901]Creation of /config endpoint in Sparta Backend

Jenkinsfile, docker/oauth2.sh
* Updated openssl link due to "404 not found" 
* Overwritten OAUTH2_ENABLE with SECURITY_OAUTH2_ENABLE passed in DCOS
=> [SPARTA-902] OAUTH2_ENABLE value set to SECURITY_OAUTH2_ENABLE
