Stratio/sparta

- driver/src/test/scala/com/stratio/sparkta/driver/test/actor/SupervisorActorSpec.scala
> SupervisorActorSpec Fixed

- driver/pom.xml
- driver/src/main/resources/reference.conf
- driver/src/main/scala/com/stratio/sparkta/driver/Sparkta.scala
- driver/src/main/scala/com/stratio/sparkta/driver/factory/CuratorFactoryHolder.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/factory/CuratorFactoryHolderIT.scala
*Created Factory using Apache Curator Framework.
*Spec to test  the factory.
> Sparkt zookeeper integration #144

- examples/policies/ITwitter-OCassandra.json
- examples/policies/ITwitter-OElasticSearch.json
- examples/policies/ITwitter-OMongo.json
- examples/policies/ITwitter-OPrint.json
- plugins/operator-firstValue/.gitignore
- plugins/operator-firstValue/pom.xml
- plugins/operator-firstValue/src/main/scala/com/stratio/sparkta/plugin/operator/firstValue/FirstValueOperator.scala
- plugins/operator-firstValue/src/test/scala/com/stratio/sparkta/plugin/operator/firstValue/FirstValueOperatorSpec.scala
- plugins/pom.xml
If we want return other type of value for Dataframes implementation, we need add in configuration in other issue
> first value operator, return string value

- examples/policies/IKafka-OCassandra.json
- plugins/parser-detector/src/main/scala/com/stratio/sparkta/plugin/parser/detector/DetectorParser.scala
There is a bug when shorting the geo field name. The reason is because is created at the end
> geo field name is not shorted

- plugins/parser-detector/src/main/scala/com/stratio/sparkta/plugin/parser/detector/DetectorParser.scala
I fixed regex to replace numbers and wrapping it with quotes
@arinconstrio   
All passed.
> Regexp fix

- plugins/parser-detector/src/main/scala/com/stratio/sparkta/plugin/parser/detector/DetectorParser.scala
The parser must have a globalNumberParser to convert Numbers to Doubles
> JSON global number parser

- pom.xml
Javier Delgado request to make this modification in order to fix the jenkins build
> Added stratio pom as parent. It fixes #238

- pom.xml
> Revert "Added stratio pom as parent. It fixes #238"

- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/dao/CassandraDAO.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/ValidatingPropertyMap.scala
Error when create two indexes with the same name for two distinct tables.
> bug in index names and reading from configuration

- plugins/operator-avg/src/main/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperator.scala
- plugins/operator-avg/src/test/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperatorSpec.scala
- plugins/operator-max/src/main/scala/com/stratio/sparkta/plugin/operator/max/MaxOperator.scala
- plugins/operator-max/src/test/scala/com/stratio/sparkta/plugin/operator/max/MaxOperatorSpec.scala
- plugins/operator-median/src/main/scala/com/stratio/sparkta/plugin/operator/median/MedianOperator.scala
- plugins/operator-median/src/test/scala/com/stratio/sparkta/plugin/operator/median/MedianOperatorSpec.scala
- plugins/operator-min/src/main/scala/com/stratio/sparkta/plugin/operator/max/MinOperator.scala
- plugins/operator-min/src/test/scala/com/stratio/sparkta/plugin/operator/min/MinOperatorSpec.scala
- plugins/operator-range/src/main/scala/com/stratio/sparkta/plugin/operator/range/RangeOperator.scala
- plugins/operator-range/src/test/scala/com/stratio/sparkta/plugin/operator/avg/RangeOperatorSpec.scala
- plugins/operator-stddev/src/main/scala/com/stratio/sparkta/plugin/operator/stddev/StddevOperator.scala
- plugins/operator-stddev/src/test/scala/com/stratio/sparkta/plugin/operator/stddev/StddevOperatorSpec.scala
- plugins/operator-sum/src/main/scala/com/stratio/sparkta/plugin/operator/sum/SumOperator.scala
- plugins/operator-sum/src/test/scala/com/stratio/sparkta/plugin/operator/sum/SumOperatorSpec.scala
- plugins/operator-variance/src/main/scala/com/stratio/sparkta/plugin/operator/variance/VarianceOperator.scala
- plugins/operator-variance/src/test/scala/com/stratio/sparkta/plugin/operator/variance/VarianceOperatorSpec.scala
- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/dao/MongoDbDAO.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Operator.scala
Now we can add strings inputs and then are converted to number in numeric operations.
> Operators with data type control in map function

- examples/policies/detector.json
- plugins/parser-detector/src/main/scala/com/stratio/sparkta/plugin/parser/detector/DetectorParser.scala
- plugins/parser-detector/src/test/scala/com/stratio/sparkta/plugin/test/parser/detector/DetectorParserSpec.scala
Hotfix en DetectorParser: now coordinates are Doubles, not Strings
> fixed bug when parsing geo in DetectorParser

- aggregator/src/test/scala/com/stratio/sparkta/aggregator/DataCubeSpec.scala
> Bug fixed. Jenkins test overview was showing weird data

- driver/src/main/scala/com/stratio/sparkta/driver/service/StreamingContextService.scala
We need small changes to improve compatibility with future changes of job-server. I made sqc optional in saveRawData. If sqc is None, it will use the factory to get an instance.
@arinconstrio 
> StreamingContextService small refactor

- test-at/src/test/resources/fixtures/ISocket-OParquetRaw.csv
- test-at/src/test/resources/policies/ISocket-OParquetRaw.json
- test-at/src/test/scala/com/stratio/sparkta/testa/ISocketOParquetRawAT.scala
First version of raw data storage acceptance test.
@arinconstrio 
> Raw data storage AcceptanceTests

- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOParquetAT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketORawDataAT.scala
Renamed package testa to testat
@Brezyll  
All passed
> changed package structure

- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOMongoAT.scala
Fix MongoDB AT race condition
@arinconstrio 
All passed
> Fixed race condition in MongoDB AT

- plugins/operator-fullText/src/main/scala/com/stratio/sparkta/plugin/operator/fullText/FullTextOperator.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/dao/MongoDbDAO.scala
- test-at/src/test/resources/fixtures/at-data-operators.csv
- test-at/src/test/resources/policies/ISocket-OMongo-operators.json
- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOMongoAT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOMongoOperatorsAT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOMongoOperatorsIT.scala
New text for operators.
Fixed some issues found:
- Fixed range-operator writings in MongoDB
- Added prefix to full-text-operator
@arinconstrio 
1 test added. All passed
> Acceptance test for testing operators with mongodb as output

- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOMongoAT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/SparktaATSuite.scala
Missed to list iterator
@arinconstrio 
37,79 %. No changes
> Fixed missed toList in iterator

- driver/src/main/scala/com/stratio/sparkta/driver/helpers/sparkta/SparktaHelper.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/service/StreamingContextServiceIT.scala
config path was not set properly in StreamingContextServiceIT
@anistal  
> StreamingContextServiceIT fails

- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOElasticsearchAT.scala
Remove the ES health check
@danielcsant  
All passed
> remove health check from ES Test

- doc/src/site/sphinx/examples.rst
- doc/src/site/sphinx/usingSparkta.rst
Changes to documentation for issues found during testing
@danielcsant 
All passed. html generated
N/A
N/A
> fixes to documentation

- driver/src/main/scala/com/stratio/sparkta/driver/service/RawDataStorageService.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/service/RawDataStorageIT.scala
- examples/policies/ITwitter-OParquet.json
- plugins/input-twitter/src/main/scala/com/stratio/sparkta/plugin/input/twitter/TwitterInput.scala
- plugins/output-cassandra/pom.xml
- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala
- plugins/output-parquet/src/main/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutput.scala
- pom.xml
- sdk/pom.xml
- sdk/src/main/scala/com/stratio/sparkta/sdk/DateOperations.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/DateOperationsSpec.scala
- test-at/pom.xml
- test-at/src/test/resources/policies/ISocket-OMongo-operators.json
- test-at/src/test/resources/policies/ISocket-OParquet.json
- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOParquetAT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketORawDataAT.scala
Spark has been uploaded to version 1.4
This PR solves these issues:
#207 
#295 
#294 
@sgomezg @arinconstrio 
1 test added. All passed
34,98%.
> Upload version of Spark to 1.4

- doc/src/site/sphinx/outputs.rst
- plugins/output-elasticsearch/pom.xml
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/dao/ElasticSearchDAO.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/ISocketOElasticsearchAT.scala
elasticsearch index mapping acording to schema
@gserranojc 
All passed
34,99%.
> elasticsearch index mapping acording to schema

- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala
- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/dao/CassandraDAO.scala
Removed non used code and index creation in setup
@gserranojc 
All passed
> removed property cluster name and creation index in setup

- examples/policies/ITwitter-OMongo-Example.json
Twitter example policy
gserranojc 
All passed
> Twitter example policy

- plugins/output-parquet/src/main/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutput.scala
- sdk/pom.xml
- test-at/pom.xml
- test-at/src/test/resources/policies/ISocket-OParquet-operators.json
> Rebase from master and tests fixed

- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala
Change write mode to Append in Cassandra output.
@anistal 
All passed
> change write mode to append

- plugins/input-socket/src/test/scala/com/stratio/sparkta/plugin/input/socket/SocketInputSpec.scala
- plugins/operator-accumulator/src/main/scala/com/stratio/sparkta/plugin/operator/accumulator/AccumulatorOperator.scala
- plugins/operator-accumulator/src/test/scala/com/stratio/sparkta/plugin/operator/accumulator/AccumulatorOperatorTestSpec.scala
- plugins/operator-avg/src/main/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperator.scala
- plugins/operator-avg/src/test/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperatorSpec.scala
- plugins/operator-count/src/main/scala/com/stratio/sparkta/plugin/operator/count/CountOperator.scala
- plugins/operator-count/src/test/scala/com.stratio.sparkta.plugin.operator.count/CountOperatorSpec.scala
- plugins/operator-max/src/main/scala/com/stratio/sparkta/plugin/operator/max/MaxOperator.scala
- plugins/operator-max/src/test/scala/com/stratio/sparkta/plugin/operator/max/MaxOperatorSpec.scala
- plugins/operator-median/src/main/scala/com/stratio/sparkta/plugin/operator/median/MedianOperator.scala
- plugins/operator-median/src/test/scala/com/stratio/sparkta/plugin/operator/median/MedianOperatorSpec.scala
- plugins/operator-min/src/main/scala/com/stratio/sparkta/plugin/operator/max/MinOperator.scala
- plugins/operator-min/src/test/scala/com/stratio/sparkta/plugin/operator/min/MinOperatorSpec.scala
- plugins/operator-range/src/main/scala/com/stratio/sparkta/plugin/operator/range/RangeOperator.scala
- plugins/operator-range/src/test/scala/com/stratio/sparkta/plugin/operator/avg/RangeOperatorSpec.scala
- plugins/operator-stddev/src/main/scala/com/stratio/sparkta/plugin/operator/stddev/StddevOperator.scala
- plugins/operator-stddev/src/test/scala/com/stratio/sparkta/plugin/operator/stddev/StddevOperatorSpec.scala
- plugins/operator-sum/src/main/scala/com/stratio/sparkta/plugin/operator/sum/SumOperator.scala
- plugins/operator-sum/src/test/scala/com/stratio/sparkta/plugin/operator/sum/SumOperatorSpec.scala
- plugins/operator-variance/src/main/scala/com/stratio/sparkta/plugin/operator/variance/VarianceOperator.scala
- plugins/operator-variance/src/test/scala/com/stratio/sparkta/plugin/operator/variance/VarianceOperatorSpec.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Operator.scala
New option in all operators that work with inputfield, now all can select distinct values.
@Brezyll 
New tests added in all operators.
All passed
> tests and operators with distinct values

- plugins/output-csv/pom.xml
- plugins/output-csv/src/main/scala/com/stratio/sparkta/plugin/output/csv/CsvOutput.scala
- test-at/pom.xml
- test-at/src/test/resources/policies/ISocket-OCsv.json
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOCsvOperatorsIT.scala
Test for CSV output
@gserranojc 
All passed
> Test for CSV output completed

- driver/src/main/scala/com/stratio/sparkta/driver/factory/SparkContextFactory.scala
- driver/src/main/scala/com/stratio/sparkta/driver/service/StreamingContextService.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/factory/SparkContextFactorySpec.scala
Minor refactor for preparing to JobServer. It's needed for work in parallel
@danielcsant     
No tes added. All passed
33.46%.
No info
> Minor refactor for preparing to JobServer

- doc/src/site/sphinx/outputs.rst
Mistake in the documentation.
@ danielcsant
New test added.
All passed
> mongoClientUri for ClientUri

- plugins/parser-morphlines/pom.xml
Add dependency explicitily to avoid old transitive dependency
@anistal 
New test added.
All passed
> Random error instanciating ElasticsearchOutput

- plugins/operator-count/src/main/scala/com/stratio/sparkta/plugin/operator/count/CountOperator.scala
- plugins/operator-count/src/test/scala/com.stratio.sparkta.plugin.operator.count/CountOperatorSpec.scala
Rename distinctDimensions to distinctFields and corrected bug in map process, now the result is with the values. 
@anistal 
New test added.
All passed
> Bug in reduce process and rename inputFields with distinct values

- pom.xml
- serving-api/pom.xml
Added plugin version, removed duplicate deps
@danielcsant 
No tes added. All passed
33.47%.
No info
> Added plugin version, removed duplicate deps

- driver/pom.xml
- driver/src/main/scala/com/stratio/sparkta/driver/service/StreamingContextService.scala
- driver/src/test/resources/reference.conf
- driver/src/test/scala/com/stratio/sparkta/driver/test/service/SparktaJobSpec.scala
- examples/policies/IKafka-OPrint.json
- serving-api/pom.xml
- serving-api/src/main/resources/reference.conf
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/Sparkta.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ControllerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/JobServerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/StreamingActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/StreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/constants/AkkaConstant.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/JobServerHttpService.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/StreamingContextServiceIT.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/actor/SupervisorActorSpec.scala
- serving-core/pom.xml
- serving-core/src/main/scala/com.stratio.sparkta.serving.core/messages/ActorsMessages.scala
* Jars uploaded to JobServer
* New JobServer actor and JobServer service in api services
@anistal 
All passed
No info
> JobServer api with encapsulated actor

- driver/src/main/scala/com/stratio/sparkta/driver/service/RawDataStorageService.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/DateOperations.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/DateOperationsSpec.scala
Parquet pattern
@anistal  
All passed
> Posibility to specify a pattern used to save data with parquet. #415

- pom.xml
Description
Refactor pom.xml to make use of Stratio parent 0.3.1
Reviewer
@danielcsant
Test
All passed
> refactor pom.xml to make use of stratio parent 0.3.1

- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/route/PolicyRoutesSpec.scala
Fixed compilation error in master
@anistal  
All passed
> fixed compilation error

- pom.xml
Description
Changes in modules order in pom.xml
Reviewer
@danielcsant 
Test
All passed
> Issue#449 mvn clean install fails in StreamingContextServiceIT

- examples/policies/IKafka-OMongo-Mode.json
- plugins/operator-mode/.gitignore
- plugins/operator-mode/pom.xml
- plugins/operator-mode/src/main/scala/com/stratio/sparkta/plugin/operator/mode/ModeOperator.scala
- plugins/operator-mode/src/test/scala/com.stratio.sparkta.plugin.operator.mode/ModeOperatorSpec.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/dao/MongoDbDAO.scala
- plugins/pom.xml
- sdk/src/main/scala/com/stratio/sparkta/sdk/WriteOp.scala
New operator, mode-operator to calculate which element/elements appears most often in a set of data.
@gserranojc   
New test added
All passed
> operator-mode

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/constants/AppConstant.scala
Change ZK's base path to /stratio/sparkta/...
@Gschiavon 
All passed
> ZK's base path changed to /stratio/sparkta

- driver/src/test/scala/com/stratio/sparkta/driver/test/service/RawDataStorageIT.scala
- plugins/output-parquet/src/test/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutputIT.scala
- pom.xml
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/Sparkta.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/StreamingContextServiceIT.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/factory/CuratorFactoryHolderIT.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/SparktaHelperSpec.scala
Description
Fix UTs and ITs
Reviewer
@danielcsant 
Test
All passed
> Issue#455 package naming not correct after splitting in driver and serving-api

- test-at/src/test/resources/policies/ISocket-OElasticsearch-operators.json
Operator Mode included in elasticsearch test
@anistal 
All passed
> Operator Mode added in elasticsearch test

- pom.xml
Description
upgrade parent pom version to 0.4.0 to use new version of jacoco
Reviewer
@danielcsant
Test
All passed
> upgrade parent pom version to 0.4.0, due to jacoco version upgrade

- doc/src/site/sphinx/sandbox.rst
Introduction for the sandbox added
@danielcsant
> Sandbox introduction

- plugins/field-dateTime/src/main/scala/com/stratio/sparkta/plugin/field/datetime/DateTimeField.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/DateOperations.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/DateOperationsSpec.scala
10 and 5 seconds support
@danielcsant 
2 added, All  passed
> added 10 and 5 seconds support in granularity

- serving-api/src/main/resources/policy_schema.json
Description
Update policy schema to allow more than one output
Reviewer
@anistal 
Test
All passed
> Issue #500 allow more than one output in a policy

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ControllerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SwaggerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
swagger not working in different port fixed.
@antonioalf    
All passed
> swagger not working in different port

- driver/src/main/scala/com/stratio/sparkta/driver/models/FragmentElementModel.scala
- examples/policies/fragments/twitterFragment.json
- serving-api/src/main/resources/templates/input/flume.json
- serving-api/src/main/resources/templates/input/kafka.json
- serving-api/src/main/resources/templates/input/rabbitmq.json
- serving-api/src/main/resources/templates/input/socket.json
- serving-api/src/main/resources/templates/input/twitter.json
- serving-api/src/main/resources/templates/output/cassandra.json
- serving-api/src/main/resources/templates/output/elasticsearch.json
- serving-api/src/main/resources/templates/output/mongodb.json
- serving-api/src/main/resources/templates/output/parquet.json
- serving-api/src/main/resources/templates/output/print.json
- serving-api/src/main/resources/templates/output/redis.json
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/TemplateHttpService.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala
Added description and short description to FragmentModel
Logo path in templates
Renamed path of inputs/outputs to input/output
It closes #511 
@MarioStratio     
All passing.
> small api improvements

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/TemplateActor.scala
The first time that you try to find a list of elements that are not created in ZK, the applicattions throws a NoNodeException. This behaviour have been changed in order to return an empty list to the frontend.
It closes issue #523 
@antonioalf  
All passed.
> return an empty array instead of a NoNode exception when listing models

- driver/src/main/scala/com/stratio/sparkta/driver/factory/SparkContextFactory.scala
- driver/src/main/scala/com/stratio/sparkta/driver/service/SparktaJob.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/factory/SparkContextFactorySpec.scala
Checkpoint folder is deleted if already exists
@gserranojc   
All passed
> Bug when restarting Sparkta. It deletes previous aggregated data

- driver/src/main/scala/com/stratio/sparkta/driver/models/FragmentElementModel.scala
- examples/policies/ITwitter-OPrintWithFragments.json
- examples/policies/fragments/twitterFragment.json
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala
New field "icon" in fragments
@MarioStratio 
Remember to clean zoookeeper's data path if there is data of a previous version.
All passed
> new field icon in fragments

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/PolicyHelper.scala
Misleading error message when adding policy with no input field and no input fragments
@antonioalf   
All passed
> Misleading error message when adding policy

- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala
Description
Missing icon field in PolicyHelperSpec
Reviewer
@Gschiavon 
Test
All passed
> Issue #528 add icon field en PolicyHelperSpec

- driver/src/main/scala/com/stratio/sparkta/driver/models/FragmentElementModel.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/PolicyHelper.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala
Validate that the policy has at least one output.
@antonioalf 
All passed
> Validation for output

- CHANGELOG.md
Description
Put releases in inverse order and add 0.6.0
Reviewer
@danielcsant
Test
All passed
> Refactor changelog

- plugins/output-mongodb/pom.xml
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/dao/MongoDbDAO.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/internal/ISocketOMongoDetectorIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOMongoOperatorsIT.scala
Update Mongo output, now it's possible to save with dataframes.
@gserranojc  
All passed
> MongoDB with dataframes

- doc/src/site/sphinx/sandbox.rst
Changed how to start sparkta sandbox
@danielcsant
> Changed sandbox doc

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyContextHttpService.scala
Description
Parse before filling when adding policyContext (same fix as was done for policies)
Reviewer
@anistal 
Test
All passed
> Issue #536 need to parse before fill in policyContext, same as in policy

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/FragmentHttpService.scala
Fragments need to be updated in the API.
@antonioalf 
No changes
No changes
No info
> Missed PUT verb in fragments

- benchmark/src/main/resources/benchmark_policy.json
- doc/src/site/sphinx/examples.rst
- doc/src/site/sphinx/outputs.rst
- doc/src/site/sphinx/policy.rst
- doc/src/site/sphinx/twitterExample.rst
- driver/src/test/resources/policies/ISocket-OMongo.json
- examples/data-generators/twitter-to-rabbit/twitter-policy.json
- examples/policies/IFlume-OMongo.json
- examples/policies/IKafka-OMongo-Detector.json
- examples/policies/IKafka-OMongo-Mode.json
- examples/policies/IKafka-OMongo-Zion.json
- examples/policies/ITwitter-OMongo-Example.json
- examples/policies/ITwitter-OMongo.json
- examples/policies/ITwitter-ORedisOMongo.json
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/dao/MongoDbDAO.scala
- serving-api/src/test/resources/policies/ISocket-OMongo.json
- test-at/src/test/resources/policies/ISocket-OMongo-Detector.json
- test-at/src/test/resources/policies/ISocket-OMongo-operators.json
- test-at/src/test/resources/reference.conf
- test-at/src/test/scala/com/stratio/sparkta/testat/SparktaATSuite.scala
MongoClient created with ServerAddress.
Property *clientUri* changed by *hosts*
No changes
No changes
No info
> Mongodb connection to replicaset

- plugins/output-elasticsearch/pom.xml
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- pom.xml
- test-at/pom.xml
- test-at/src/test/resources/reference.conf
- test-at/src/test/scala/com/stratio/sparkta/testat/SparktaATSuite.scala
Added lucene and elasticsearch dependencies to be compatible with Elasticsearch 1.7.1
No changes
No changes
No info
> Elasticsearch compatible with version 1.7.1

- aggregator/src/main/scala/com/stratio/sparkta/aggregator/Cube.scala
The test is failing due to missing default value for rememberPartitioner
> Test fixed. It closes #647

- dist/pom.xml
- dist/src/main/unix/etc/init.d/sparkta
- Sparkta process is killed
- Error logs go to sparkta.err
No changes
No changes
No info
> stop script fixed

- driver/src/test/scala/com/stratio/sparkta/driver/test/models/AggregationPoliciesSpec.scala
- examples/policies/ITwitter-OPrintWithFragments.json
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/PolicyHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/FragmentHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/route/PolicyRoutesSpec.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/AggregationPoliciesModel.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/FragmentElementModel.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/TemplateModel.scala
Added UUIDs in fragments and policies in order to update the name of the model. It closes #675 
@Gschiavon
> id in fragments

- examples/policies/ITwitter-OPrintWithFragments.json
- examples/policies/fragments/twitterFragment.json
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
Added policy download endpoint. Closes #676
> added policy download endpoint

- doc/src/site/sphinx/advanced.rst
- doc/src/site/sphinx/examples.rst
- doc/src/site/sphinx/index.rst
- doc/src/site/sphinx/usingSparkta.rst
- Zookeeper metadata documentation.
- New "Advanced documentation" bullet in user documentation
> Advanced doc and some fixes

- doc/src/site/sphinx/outputs.rst
Updated mongoDb doc, because now we use dataframes
No changes
No changes
No info
> Updated MongoDb doc

- serving-api/src/main/resources/templates/input/flume.json
- serving-api/src/main/resources/templates/input/kafka.json
- serving-api/src/main/resources/templates/input/kafkaDirect.json
- serving-api/src/main/resources/templates/input/rabbitmq.json
- serving-api/src/main/resources/templates/output/cassandra.json
- serving-api/src/main/resources/templates/output/csv.json
- serving-api/src/main/resources/templates/output/elasticsearch.json
- serving-api/src/main/resources/templates/output/mongodb.json
Removed defaults and regexp for selects and booleans
No changes
No changes
No info
> Input-output templates refactor

- doc/src/site/sphinx/inputs.rst
- doc/src/site/sphinx/outputs.rst
- serving-api/src/main/resources/templates/input/kafkaDirect.json
- serving-api/src/main/resources/templates/output/csv.json
Links to documentation of each input and output has been added and documentation has been updated since MongoDB now uses DataFrames. CSV output has also been included in the documentation.
No changes
No changes
No info
> Update documentation of inputs and outputs

- doc/src/site/sphinx/sandbox.rst
Windows10 bug added to documentation. Links added for more information to the users.
No changes
No changes
No info
> Windows10 bug added to documentation

- web/src/index.html
- web/src/scripts/controllers/inputs.js
- web/src/stratio-ui/script/directives/forms/datasource-form-field-directive.js
- web/src/stratio-ui/script/directives/forms/form-field-check-directive.js
- web/src/stratio-ui/template/form/datasource_form_field.html
- web/src/stratio-ui/template/form/form_field_check.html
- web/src/stratio-ui/template/form/form_field_select.html
> feature(new input): changing new input modal funcionality according to new JOSN

- dist/pom.xml
added examples folder to packaging
No changes
No changes
No info
> Examples does not appear when installing packages

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/FragmentHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/ErrorModel.scala
Description
added find by name in policies and fragments
Test
No changes
Coverage
No changes
Scalastyle
No info
> add find by name in policies and fragments

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/FragmentHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
Fix. When a model is created though the API, the created model must be returned
> when create a model the object must be returned

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
All models must be persisted with lowercase names.
> lowercases always in models

- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/JsoneyString.scala
Allow Booleans in JsoneyString
> allow boolean in jsoneyString

- examples/policies/IFlume-OMongo.json
- plugins/input-flume/src/main/scala/com/stratio/sparkta/plugin/input/flume/FlumeInput.scala
Flume fields are all Strings in the policy
No changes
No changes
No info
> Flume refactor

- examples/policies/fragments/twitterFragment.json
- sdk/src/main/scala/com/stratio/sparkta/sdk/JsoneyString.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
If a property configurations has an array inside it must be serialized to an object
> added serialize json objects in jsoneystring

- dist/pom.xml
Description
Remove zip generation phase from dist/pom.xml
Test
No changes
Coverage
No changes
Scalastyle
No info
> remove zip generation

- examples/data-generators/twitter-to-rabbit/twitter-policy.json
- plugins/input-rabbitMQ/src/main/scala/com/stratio/sparkta/plugin/input/rabbitmq/RabbitMQInput.scala
Rabbit connection port is now a String
No changes
No changes
No info
> Rabbit policy refactor

- sdk/src/main/scala/com/stratio/sparkta/sdk/JsoneyString.scala
Booleans can be parsed with jsoney
passed
No changes
No info
> changes in jsoney to parse booleans

- web/pom.xml
removed karma
All test passed
No changes
No info
> Fix web module installation

- examples/policies/IKafkaDirect-OElasticsearch.json
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/dao/ElasticSearchDAO.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/ValidatingPropertyMap.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/HostPortConfSpec.scala
- test-at/src/test/resources/policies/ISocket-OElasticsearch-operators.json
- test-at/src/test/resources/policies/ISocket-OElasticsearch.json
- test-at/src/test/resources/policies/ISocket-OElasticsearchJSON.json
- test-at/src/test/resources/policies/ISocket-OMongo-Detector.json
Elasticsearch connection chain is now a List of tuples (host,port)
All passed and one added
No changes
No info
> Refactor of elasticsearch connection chain

- plugins/field-geoHash/src/main/scala/com/stratio/sparkta/plugin/field/geohash/GeoHashField.scala
- plugins/field-geoHash/src/test/scala/com/stratio/sparkta/plugin/field/geohash/GeoHashFieldSpec.scala
- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/dao/CassandraDAO.scala
- code taken from shoppingcenters demo
- cassandra type bigint change to int
- workaround for persisting geolocation in cassandra
All passed and one added
No changes
No info
> geolocation in cassandra

- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/StreamingContextServiceIT.scala
Integration test was failing
All passed and one added
No changes
No info
> Fix integration test

- examples/policies/IRabbit-OPrint.json
- plugins/input-rabbitMQ/src/main/scala/com/stratio/sparkta/plugin/input/rabbitmq/RabbitMQInput.scala
- plugins/input-rabbitMQ/src/test/scala/com/stratio/sparkta/plugin/input/rabbitmq/getRabbitRoutingKeysSpec.scala
RoutingKeys field in the policy is now a sequence of Strings
All passed and one added 
No changes
> Refactor of redis RoutingKeys field

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/PolicyHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/FragmentHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyContextHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/TemplateHttpService.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/test/helpers/PolicyHelperSpec.scala
- Changed Await.result to Future. Now, spray returns Future.
- Changed validation block to if sentence with BadRequest response.
All passed
No changes
No info
> Refactor on complete in spray-routing. Now, it returns future.

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
When I run a policy and then try to delete it, it will keep appearing when listing all policies
All passed
No changes
No info
> delete running policy

- test-at/pom.xml
- Change depency
All passed
No changes
No info
> fix dependency

- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
- test-at/src/test/resources/policies/ISocket-OElasticsearch-operators.json
Autocalculated id it's set to true by default in elasticSearch
All passed
No changes
No info
> Autocalculated id it's set to true in elasticSearch

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
Added toLowerCase to name when create a policy by the policyContext endpoint. Added NoSuchElementException to recover
All passed.
No changes
No info
> Fixing error when creating a policy by policyContext endpoint

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
Fixed bug when the policy had blank spaces
@dvallejo and @arinconstrio  
All passed
No changes
No info
> Policy names

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/FragmentHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/TemplateHttpService.scala
Added mandatory fields with the annotation called required
All passed.
No changes
No info
> Mandatory fields in Swagger

- doc/src/site/sphinx/cube.rst
- sdk/src/main/scala/com/stratio/sparkta/sdk/FilterModel.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Operator.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/OperatorSpec.scala
Refactor of dimensionValue to fieldValue
All passed. Test-At passed.
No changes
No info
> Refactor of dimensionValue to fieldValue

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
- Bug about listing all policies fixed
All passed
No changes
No info
> Bug about listing all policies fixed

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
Added exception for fragments when you try to find a fragment by type and name that doesn't exist.
All passed.
No changes
No info
> Added exception for fragments

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActor.scala
bug when creating new policies is fixed.
All passed.
No changes
No info
> bug when creating new policies is fixed

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
return status in findByFragments
All passed.
No changes
No info
> return status in findByFragments

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
Check if exists when the first fragment is added
All passed.
No changes
> Check if exists when the first fragment is added

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
Added re-run policy control
All passed.
No changes
No info
> You can't run policy more than once

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/FragmentActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolder.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActor.scala
Check path context zookeeper for contexts, policies and fragments
All passed.
No changes
No info
> Check if exists zookeeper paths

- driver/pom.xml
- driver/src/main/scala/com/stratio/sparkta/driver/factory/SchemaFactory.scala
- driver/src/main/scala/com/stratio/sparkta/driver/service/SparktaJob.scala
- examples/policies/ITwitter-OSolr.json
- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/dao/CassandraDAO.scala
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala
- plugins/output-solr/src/main/scala/com/stratio/sparkta/plugin/output/solr/SolrDAO.scala
- plugins/output-solr/src/main/scala/com/stratio/sparkta/plugin/output/solr/SolrOutput.scala
- pom.xml
- sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/TableSchema.scala
- serving-api/pom.xml
- serving-api/src/main/resources/log4j.properties
- test-at/pom.xml
- test-at/src/test/resources/policies/ISocket-OSolr-operators.json
Cube name is taken as table name. Added dependency needed for reflection. Solr output minor changes. It closes #741
@gserranojc     
No changes
No changes
No info
> Table name from cube and Solr minor changes

- plugins/output-solr/src/main/scala/com/stratio/sparkta/plugin/output/solr/SolrOutput.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/AggregateOperations.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
Solr agg dimension from cube if it defined.
@gserranojc     
No changes
No changes
No info
> Solr agg dimension from cube if defined

- examples/data-generators/ecommerce/ecommerce-policy.json
- examples/data-generators/twitter-to-rabbit/twitter-policy.json
Fixed RabbitMQ examples policies
@danielcsant    
No changes
No changes
No info
> Fixed RabbitMQ examples policies

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyContextHttpService.scala
Returns policyId when creating a new policy context
Resolved error when trying to list policy contexts. Created status NotStarted when the policy is a new one.
All passed.
No changes
No info
> Returns policyId when creating a new policy context

- .gitignore
- dist/pom.xml
Changed JMX port to 7183
All passed.
No changes
No info
> Changed JMX port

- examples/policies/IFlume-OMongo.json
- plugins/input-flume/src/main/scala/com/stratio/sparkta/plugin/input/flume/FlumeInput.scala
Changed format about addresses in flume input
All passed.
No changes
No info
> Changed format of Flume policy

- CHANGELOG.md
Added comments for version 0.6.1
> changelog for version 0.6.1

- driver/src/main/scala/com/stratio/sparkta/driver/util/HdfsUtils.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ClusterSparkStreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
Check if fails some process
All passed.
No changes
No info
> Try cluster execution

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
Policy queries with fragments updated. Bug #907 
All passed. Tested the new functions.
No changes
No info
> Policy with fragments updated

- driver/src/main/scala/com/stratio/sparkta/driver/constants/AkkaConstant.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/Sparkta.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ControllerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SwaggerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/constants/HttpConstant.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/ResetStatusHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/AppStatusHttpService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/ServiceRoutes.scala
Added app status enndpoint
All passed. 
No changes
No info
> Status EndPoint

- web/src/index.html
- web/src/templates/components/c-input-field.tpl.html
- web/src/templates/components/c-input-list-field.tpl.html
- web/src/templates/components/c-slider.tpl.html
- web/src/templates/components/c-step-progress-bar.tpl.html
- web/src/templates/components/c-step.tpl.html
- web/src/templates/components/st-delete-modal.tpl.html
- web/src/templates/components/st-duplicate-modal.tpl.html
- web/src/templates/confirm-modal.tpl.html
- web/src/templates/fragments/fragment-details.tpl.html
- web/src/templates/policies/dimension-modal.tpl.html
- web/src/templates/policies/operator-modal.tpl.html
- web/src/templates/policies/st-confirm-policy-modal.tpl.html
- web/src/templates/policies/st-delete-policy-modal.tpl.html
- web/src/views/policies/cube-accordion.html
- web/src/views/policies/cube-panel.html
- web/src/views/policies/model-accordion.html
- web/src/views/policies/model-panel.html
- web/src/views/policies/output.html
- web/src/views/policies/wizard-panel.html
Add prefix "data" to angular directives in order to generate a valid HTML
> Add prefix "data" to angular directives

- dist/pom.xml
- dist/src/main/unix/etc/init.d/sparkta
- dist/src/main/unix/scripts/postinst
Now is possible start and stop Sparkta service with sudo and stratio user. 
All passed. 
No changes
No info
> Sparkta Service start/stop with sudo and with stratio user

- test-at/pom.xml
Test-at module dependecies were deprecated
Maybe related to #1053 
All passed. 
No changes
No info
> Update test-at module dependencies

- doc/src/site/sphinx/examples.rst
Documentation about the Scripts that creates policies in the website added in Examples.rst
> Script doc added

- doc/src/site/sphinx/inputs.rst
- doc/src/site/sphinx/outputs.rst
- web/src/data-templates/input.json
- web/src/data-templates/output.json
Descriptions added in templates
User doc fixed
All passed.
No changes
No info
> fixed input/output doc and templates

- driver/src/main/scala/com/stratio/sparkta/driver/SparktaClusterJob.scala
Added Success to Try
All passed.
No changes
No info
> Bug deploying in Mesos

- doc/src/site/sphinx/policy.rst
Documentation about name of the tables in Sparkta's outputs
> doc table names

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/Sparkta.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/PolicyHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/ResetStatusHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
Now you can only run one Sparkta, and if you try to open another instance , an error message will be displayed and the application will be closed.
All passed.
No changes
No info
> Now you can only run one Sparkta

- plugins/operator-accumulator/src/main/scala/com/stratio/sparkta/plugin/operator/accumulator/AccumulatorOperator.scala
- plugins/operator-accumulator/src/test/scala/com/stratio/sparkta/plugin/operator/accumulator/AccumulatorOperatorTestSpec.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/ValidatingPropertyMap.scala
Coverage of current test: 100%
> Accumulator operator test coverage

- sdk/src/main/scala/com/stratio/sparkta/sdk/DimensionValue.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/AggregateOperationsSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/DateOperationsSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/DimensionSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/DimensionTypeSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/DimensionValueSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/EntityCountSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/EventSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/InputTest.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/MultiplexerSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/OperatorSpec.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/test/DimensionTypeTest.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/test/EntityCountTest.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/test/InputTest.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/test/OperatorTest.scala
> Test sdk coverage stage 1

- driver/src/test/scala/com/stratio/sparkta/driver/test/factory/SparkContextFactorySpec.scala
- pom.xml
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolder.scala
- serving-core/src/test/scala/com/stratio/sparkta/driver/helpers/sparkta/CuratorFactoryHolderIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/SparktaATSuite.scala
Bugs corrected in test-At and curatorFactoryHolderIt
All passed.
No changes
No info
> Test curator factory

- plugins/output-elasticsearch/pom.xml
- plugins/parser-morphlines/pom.xml
- pom.xml
New dependencies in Morphline and elasticsearch output.
All passed.
No changes
No info
> New lucene dependencies in modules

- plugins/operator-accumulator/src/main/scala/com/stratio/sparkta/plugin/operator/accumulator/AccumulatorOperator.scala
- plugins/operator-avg/src/main/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperator.scala
- plugins/operator-count/src/main/scala/com/stratio/sparkta/plugin/operator/count/CountOperator.scala
- plugins/operator-count/src/test/scala/com.stratio.sparkta.plugin.operator.count/CountOperatorSpec.scala
- plugins/operator-entityCount/src/main/scala/com/stratio/sparkta/plugin/operator/entityCount/EntityCountOperator.scala
- plugins/operator-entityCount/src/test/scala/com/stratio/sparkta/plugin/operator/entityCount/EntityCountOperatorSpec.scala
- plugins/operator-firstValue/src/main/scala/com/stratio/sparkta/plugin/operator/firstValue/FirstValueOperator.scala
- plugins/operator-fullText/src/main/scala/com/stratio/sparkta/plugin/operator/fullText/FullTextOperator.scala
- plugins/operator-fullText/src/test/scala/com/stratio/sparkta/plugin/operator/fullText/FullTextOperatorSpec.scala
- plugins/operator-lastValue/src/main/scala/com/stratio/sparkta/plugin/operator/lastValue/LastValueOperator.scala
- plugins/operator-max/src/main/scala/com/stratio/sparkta/plugin/operator/max/MaxOperator.scala
- plugins/operator-median/src/main/scala/com/stratio/sparkta/plugin/operator/median/MedianOperator.scala
- plugins/operator-min/src/main/scala/com/stratio/sparkta/plugin/operator/max/MinOperator.scala
- plugins/operator-mode/src/main/scala/com/stratio/sparkta/plugin/operator/mode/ModeOperator.scala
- plugins/operator-mode/src/test/scala/com.stratio.sparkta.plugin.operator.mode/ModeOperatorSpec.scala
- plugins/operator-range/src/main/scala/com/stratio/sparkta/plugin/operator/range/RangeOperator.scala
- plugins/operator-stddev/src/main/scala/com/stratio/sparkta/plugin/operator/stddev/StddevOperator.scala
- plugins/operator-sum/src/main/scala/com/stratio/sparkta/plugin/operator/sum/SumOperator.scala
- plugins/operator-sum/src/test/scala/com/stratio/sparkta/plugin/operator/sum/SumOperatorSpec.scala
- plugins/operator-totalEntityCount/src/test/scala/com/stratio/sparkta/plugin/operator/totalEntityCount/TotalEntityCountOperatorSpec.scala
- plugins/operator-variance/src/main/scala/com/stratio/sparkta/plugin/operator/variance/VarianceOperator.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/EntityCount.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Operator.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/OperatorConstants.scala
All operators with 100% of coverage
> All operators with 100% of coverage

- plugins/operator-accumulator/src/main/scala/com/stratio/sparkta/plugin/operator/accumulator/AccumulatorOperator.scala
- plugins/operator-avg/src/main/scala/com/stratio/sparkta/plugin/operator/avg/AvgOperator.scala
- plugins/operator-fullText/src/main/scala/com/stratio/sparkta/plugin/operator/fullText/FullTextOperator.scala
- plugins/operator-lastValue/src/main/scala/com/stratio/sparkta/plugin/operator/lastValue/LastValueOperator.scala
- plugins/operator-max/src/main/scala/com/stratio/sparkta/plugin/operator/max/MaxOperator.scala
- plugins/operator-median/src/main/scala/com/stratio/sparkta/plugin/operator/median/MedianOperator.scala
- plugins/operator-min/src/main/scala/com/stratio/sparkta/plugin/operator/max/MinOperator.scala
- plugins/operator-mode/src/main/scala/com/stratio/sparkta/plugin/operator/mode/ModeOperator.scala
- plugins/operator-range/src/main/scala/com/stratio/sparkta/plugin/operator/range/RangeOperator.scala
- plugins/operator-stddev/src/main/scala/com/stratio/sparkta/plugin/operator/stddev/StddevOperator.scala
- plugins/operator-sum/src/main/scala/com/stratio/sparkta/plugin/operator/sum/SumOperator.scala
- plugins/operator-variance/src/main/scala/com/stratio/sparkta/plugin/operator/variance/VarianceOperator.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Operator.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/ProcessMapAsAny.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/ProcessMapAsNumber.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/OperatorSpec.scala
All tests passed. Test AT passed without parallelism.
> Bug related to bad refactor fixed.

- driver/src/test/scala/com/stratio/sparkta/driver/test/factory/SparkContextFactorySpec.scala
- plugins/output-elasticsearch/pom.xml
- plugins/parser-morphlines/pom.xml
- pom.xml
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolder.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolderIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/SparktaATSuite.scala
The current PR is a rebase from Master branch into feature/test-coverage branch
> Rebase from master to  test coverage branch

- web/karma.conf.js
- web/test/directive/c-step-progress-bar-directive.js
- web/test/inputs/inputs-controller.js
Change the name to utils service's functions to new ones
> Fix unit test of input controller

- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala
- plugins/output-cassandra/src/main/test/com/stratio/sparkta/plugin/output/cassandra/AnswerSugar.scala
- plugins/output-cassandra/src/main/test/com/stratio/sparkta/plugin/output/cassandra/CassandraDaoSpec.scala
- plugins/output-cassandra/src/main/test/com/stratio/sparkta/plugin/output/cassandra/CassandraOutputSpec.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/ConfigFactorySpec.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/SparktaConfigSpec.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/models/test/AggregationPolicySpec.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/models/test/ErrorsModelSpec.scala
CassandraOutputSpect from 0 to 74 % of coverage.
CassandraDaoSpec from 15 to 85% of coverage
Test CassandraOutputSpec added
Test CassandraDaoSpec Added
All test-AT passed
> cassandra output test

- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/dao/ElasticSearchDAO.scala
- plugins/output-elasticsearch/src/test/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutputSpec.scala
- plugins/output-elasticsearch/src/test/scala/com/stratio/sparkta/plugin/output/elasticsearch/dao/ElasticSearchDaoSpec.scala
Elasticsearch test coverage. Removed unused functions and refactored others to improve readability or testability.
> ElasticSearch output coverage

- doc/src/site/sphinx/production.rst
Added production check-list to doc
> production checklist

- doc/src/site/sphinx/cluster-config.rst
- doc/src/site/sphinx/configuration.rst
- doc/src/site/sphinx/index.rst
added documentation about cluster configuration
> added documentation about cluster configuration

- doc/src/site/sphinx/cassandra.rst
- doc/src/site/sphinx/dataframes.rst
- doc/src/site/sphinx/faq.rst
- doc/src/site/sphinx/index.rst
- doc/src/site/sphinx/troubleshooting.rst
Added doc for Production Checklist & Troubleshooting Guide section
Linked FAQ section
removed unused cassandra and dataframes files
> production checklist and troubleshooting

- doc/src/site/sphinx/usingSparkta.rst
Update the version of the services included in the sandbox
> update services version

- doc/src/site/sphinx/cheatsheet.rst
- doc/src/site/sphinx/index.rst
- doc/src/site/sphinx/usingSparkta.rst
> Cheatsheet doc entry

- plugins/input-kafka/src/main/scala/com/stratio/sparkta/plugin/input/kafka/KafkaInput.scala
Kafka input had a bug when parsing Group.id parameter
@danielcsant
All Passed
> Kafka input fixed

- driver/src/main/scala/com/stratio/sparkta/driver/SparktaClusterJob.scala
- serving-api/pom.xml
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ControllerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SwaggerActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/AppStatusHttpService.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/actor/ControllerActorSpec.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/actor/FragmentActorSpec.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/actor/SwaggerActorSpec.scala
- serving-api/src/test/scala/com/stratio/sparkta/serving/api/service/http/AppStatusHttpServiceSpec.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolder.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActor.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolderIT.scala
Fix curatorFramework is mocked in all test, now we need zookeeper online for some tests. 
@arinconstrio 
Passed
> Curator framework mocked

- examples/policies/ITwitterJson-OCassandra.json
- examples/policies/ITwitterJson-OCsv.json.json
Fix examples in twitter policies.
@arinconstrio 
Passed
> Twitter examples error in JsonPaths

- web/src/data-templates/output.json
- web/src/languages/en-US.json
Show Cassandra cluster name in web ui
@gserranojc @danielcsant  
Passed
> add Cassandra cluster name to web gui

- plugins/output-redis/src/main/scala/com/stratio/sparkta/plugin/output/redis/RedisOutput.scala
- plugins/output-redis/src/main/scala/com/stratio/sparkta/plugin/output/redis/dao/AbstractRedisDAO.scala
- web/src/data-templates/output.json
Refactor redis output for control empty dimensions values and added more operations.
Now is more legible.
@arinconstrio 
Passed
> Redis refactor

- plugins/output-csv/src/main/scala/com/stratio/sparkta/plugin/output/csv/CsvOutput.scala
Check the delimiter in csv output, the size must be one.
@arinconstrio 
Passed
> CSV Output check in delimiter fields

- driver/src/main/scala/com/stratio/sparkta/driver/service/StreamingContextService.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActor.scala
fixes SPARKTA-139, kill policy actor when the user want to stop a job
@gserranojc
> kill akka stopped actors (2)

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyHttpService.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/helpers/PolicyHelper.scala
Fix the error in the policy downloaded, in some cases the fillFragments generate errors. 
All are been corrected, but now we can discuss if we want only fragments for the input/outputs.
@arinconstrio
> Download policy error and corrected errors in fillFragments

- dist/src/main/resources/log4j.xml
Description
Related SPARKTA-131, added DailyRollingFileAppender
Reviewer
@arinconstrio
> SPARKTA-131 Added DailyRollingFileAppender

- doc/src/site/sphinx/outputs.rst
- examples/policies/IKafkaDirect-OElasticsearch.json
- examples/policies/fragments/ElasticSearchFragment.json
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- plugins/output-redis/src/main/scala/com/stratio/sparkta/plugin/output/redis/RedisOutput.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/constants/ActorsConstant.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/service/http/PolicyContextHttpService.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolder.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/internal/ISocketOElasticsearchJsonAT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOElasticsearchOperatorsIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketORedisOperatorsIT.scala
Added versioned policies in ElasticSearch, now the mapping include the version of the policy.
Corrected bug in policyContextActor.
@arinconstrio
> Elasticsearch with versioned policies

- testsAT/src/test/resources/features/manual/endToEnd/outCassandra.feature
- testsAT/src/test/resources/features/manual/endToEnd/outParquet.feature
- testsAT/src/test/resources/features/manual/policies/downloadPolicy.feature
- testsAT/src/test/resources/features/manual/policies/editPolicy.feature
- testsAT/src/test/resources/features/manual/policies/transformations/timestampTransformation.feature
Added features for:
- End 2 End:
- Cassandra
- Parquet
- Policy management:
- stop-edit-start
- Policy JSON download
- Policy preview
> Bugfest pfperez

- dist/pom.xml
- plugins/operator-median/pom.xml
- plugins/operator-stddev/pom.xml
- plugins/operator-variance/pom.xml
Related SPARKTA-98, exclude jtransform dependency 
@danielcsant
> remove jtransform dependency

- serving-core/src/main/scala/com/stratio/sparkta/serving/core/helpers/JarsHelper.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/helpers/JarsHelpersSpec.scala
Added control with the jars search, because the file path must exists.
@arinconstrio
> Added control in the jars search with the file.exists

- doc/src/site/sphinx/outputs.rst
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/dao/MongoDbDAO.scala
- web/src/data-templates/output.json
Now we only have one connection for create the indexes, this support all the versioned policies.
The DAO is refactored because had a lot of unused functions.
@arinconstrio
> Mongodb with versioned policies

- doc/src/site/sphinx/outputs.rst
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/dao/ElasticSearchDAO.scala
- plugins/output-elasticsearch/src/test/scala/com/stratio/sparkta/plugin/output/elasticsearch/dao/ElasticSearchDaoSpec.scala
- plugins/output-parquet/src/main/scala/com/stratio/sparkta/plugin/output/parquet/ParquetOutput.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/OutputSpec.scala
Now we support all the versioned policies, because the can have distinct schema for the dataframes.
@arinconstrio
> Parquet with versioned policies

- doc/src/site/sphinx/outputs.rst
- plugins/output-csv/src/main/scala/com/stratio/sparkta/plugin/output/csv/CsvOutput.scala
Now we support all the versioned policies. We modify the path adding the version for the cube.
@arinconstrio
> Csv versioned policies

- pom.xml
New profiles for spark multiple versions supports.
> SPARKTA-75 New profiles for spark multiple versions supports

- dist/src/main/resources/application.conf
- sandbox/stratio_sandbox_module
- serving-api/src/main/resources/reference.conf
Changes for be able to automate sandbox creation. SPARKTA-84
@danielcsant 
All passed.
No changes
No info
> Changes for Sandbox automatization

- sandbox/stratio_sandbox_module
Bugfixing sandbox automatization. SPARKTA-84
@Gschiavon, @antonioalf 
All passed.
No changes
No info
> Bugfixing sandbox automatization

- driver/src/test/scala/com/stratio/sparkta/driver/test/util/PolicyUtilsTest.scala
- examples/policies/IKafka-OPrint.json
Refactor policy IKafka-OPrint to make it simpler
@Gschiavon  
All passed.
No changes
No info
> SPARKTA-195 Fix IKafka-OPrint policy example

- sandbox/functions.sh
- sandbox/make-sandbox
- sandbox/stratio_sandbox_module
Scripts for build sandbox. SPARKTA-84
@anistal  
All passed.
No changes
No info
> sandbox scripts

- plugins/input-flume/src/main/scala/com/stratio/sparkta/plugin/input/flume/FlumeInput.scala
- plugins/input-kafka/src/main/scala/com/stratio/sparkta/plugin/input/kafka/KafkaDirectInput.scala
- plugins/input-kafka/src/main/scala/com/stratio/sparkta/plugin/input/kafka/KafkaInput.scala
- plugins/input-rabbitMQ/src/main/scala/com/stratio/sparkta/plugin/input/rabbitmq/RabbitMQInput.scala
- plugins/output-cassandra/src/main/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutput.scala
- plugins/output-cassandra/src/test/scala/com/stratio/sparkta/plugin/output/cassandra/CassandraOutputTest.scala
- plugins/output-elasticsearch/src/main/scala/com/stratio/sparkta/plugin/output/elasticsearch/ElasticSearchOutput.scala
- plugins/output-mongodb/src/main/scala/com/stratio/sparkta/plugin/output/mongodb/MongoDbOutput.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/ValidatingPropertyMap.scala
- sdk/src/test/scala/com/stratio/sparkta/sdk/ValidatingPropertyMapTest.scala
- web/src/data-templates/output.json
- web/src/languages/en-US.json
Possibility to set the cluster name and all the cassandra-spark options (https://github.com/datastax/spark-cassandra-connector/blob/master/doc/reference.md#read-tuning-parameters)
@gserranojc   
All passed.
No changes
No info
> SPARKTA-110 Improve Cassandra Output

- sandbox/make-sandbox
- sandbox/stratio_sandbox_module
ZK service must be started by default. Sparkta tar is not created correctly. SPARKTA-242
@antonioalf 
All passed.
No changes
No info
> [SANDBOX] Bugfix sandbox creation

- dist/src/main/resources/application.conf
- dist/src/main/unix/etc/init.d/sparkta
- sandbox/functions.sh
- sandbox/make-sandbox
- sandbox/stratio_sandbox_module
- serving-api/src/main/resources/reference.conf
Cherry picks of some commits for solving issues: PID folder creation and sandbox automatization.
> [Bugfix] PID and Sandbox bugfixing

- testsAT/pom.xml
Needed due to changes in parent library
> Fix testsAT pom for testng

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
- test-at/pom.xml
Removed actor when deleting the policy
@sgomezg 
All passed.
No changes
No info
> SPARKTA-139 Policy actors seem to not be dying

- test-at/pom.xml
Updated Cassandra unit test library. Test-at were failing
@antonioalf  
All passed.
No changes
No info
> Updated Cassandra unit test library. Test-at were failing

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
Rebase from branch-0.7 into master
> Rebase from branch-0.7

- pom.xml
Removed license plugin in zinc profile
@sgomezg     
All OK
No changes
No info
> SPARKTA-225 Reduced packaging time in zinc profile

- pom.xml
Sync branch 0.8 with master. SPARKTA-266
> Make Spark-1.5 packaging be the default

- plugins/output-elasticsearch/pom.xml
- plugins/output-mongodb/pom.xml
- pom.xml
- test-at/pom.xml
Mongo and Elastic fix  (v0.8.0-RC2). SPARKTA-273
@acemilio    
All OK
No changes
No info
> [Bugfix] Mongo and Elastic fix. SPARKTA-273

- plugins/output-elasticsearch/pom.xml
- plugins/output-mongodb/pom.xml
- pom.xml
Mongo and Elastic fix. Cherry-pick from branch-0.8.0. SPARKTA-273
@acemilio    
All OK
No changes
No info
> Mongo and Elastic fix. SPARKTA-273

- sdk/src/main/scala/com/stratio/sparkta/sdk/Output.scala
Check the Row size with Schema fields size in DataFrame creation.
@anistal  
All passed.
> [SPARKTA-237] [SDK] Check the Row with the future DataFrame Schema

- dist/src/main/resources/application.conf
- driver/src/main/scala/com/stratio/sparkta/driver/SparktaClusterJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/util/HdfsUtils.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/util/HdfsUtilsTest.scala
- project/scalastyle_config.xml
- serving-api/src/main/resources/reference.conf
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ClusterSparkStreamingContextActor.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/SparktaConfig.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/constants/AppConstant.scala
Hdfs utils changed to allow remote connections. SPARKTA-209
Doc updated: https://stratio.atlassian.net/wiki/display/SPARKTA0x9/6.+Configuration#id-6.Configuration-5.6.Clusterconfiguration
@anistal, @danielcsant 
All OK
> [SPARKTA-209][Driver] Hdfs utils changed to allow remote connections.

- web/src/data-templates/input.json
- web/src/data-templates/output.json
- web/src/data-templates/policy.json
Updated links to Confluence documentation
All OK
> SPARKTA-289 [WEB] Help links are broken

- aggregator/src/main/scala/com/stratio/sparkta/aggregator/Cube.scala
- plugins/operator-accumulator/src/main/scala/com/stratio/sparkta/plugin/operator/accumulator/AccumulatorOperator.scala
- plugins/operator-totalEntityCount/src/main/scala/com/stratio/sparkta/plugin/operator/totalEntityCount/TotalEntityCountOperator.scala
- plugins/operator-totalEntityCount/src/test/scala/com/stratio/sparkta/plugin/operator/totalEntityCount/TotalEntityCountOperatorTest.scala
Spark transformations map and mapValues with groupByKey could be one transformation CombineByKey, the performance is better.
@danielcsant 
All passed.
> [AGGREGATOR, PLUGINS] Spark transformations CombineByKey with Associative Aggregations

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOCassandraOperatorsIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOCsvOperatorsIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOMongoFiltersJsonIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOMongoOperatorsIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOParquetOperatorsIT.scala
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketORedisOperatorsIT.scala
Close correctly client database connections to the embedded databases. The Spark Contexts for check results are closed correctly in tests.
@dvallejo 
All passed.
> Close db connections and Spark Context in test-at

- dist/src/main/resources/application.conf
- driver/pom.xml
- driver/src/main/scala/com/stratio/sparkta/driver/SparktaClusterJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/repository/ClusterConfigRepositoryComponent.scala
- driver/src/test/resources/reference.conf
- pom.xml
- serving-api/src/main/resources/reference.conf
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ClusterSparkStreamingContextActor.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolder.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/actor/FragmentActor.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/constants/AppConstant.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolderIT.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/SparktaConfigTest.scala
- test-at/src/test/resources/reference.conf
> [BUGFIX][Driver] HDFS config from ZK fix

- plugins/output-kafka/pom.xml
- plugins/output-kafka/src/main/scala/com/stratio/sparkta/plugin/output/kafka/KafkaOutput.scala
- plugins/output-kafka/src/main/scala/com/stratio/sparkta/plugin/output/kafka/producer/KafkaProducer.scala
- plugins/output-kafka/src/test/scala/KafkaProducerTest.scala
- plugins/pom.xml
- web/src/data-templates/output.json
- web/src/languages/en-US.json
[SPARKTA-256][PLUGINS] Kafka output
All passed. 90% coverage
> [SPARKTA-256][PLUGINS] Kafka output

- driver/src/main/scala/com/stratio/sparkta/driver/SparktaClusterJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/dao/ZookeeperDao.scala
- pom.xml
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ClusterLauncherActor.scala
Commons utils upgraded. ZookeeperDAO created. Related to https://github.com/Stratio/Sparkta/pull/1366#discussion-diff-50370648
@dvallejo  
All OK
> Stratio commons utils updated

- pom.xml
- test-at/src/test/scala/com/stratio/sparkta/testat/outputs/ISocketOCassandraOperatorsIT.scala
> SPARKTA-333 Compatibility with openjdk-8

- driver/src/main/scala/com/stratio/sparkta/driver/SparktaClusterJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/factory/SparkContextFactory.scala
- driver/src/main/scala/com/stratio/sparkta/driver/service/StreamingContextService.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/policy/status/PolicyStatusActor.scala
Exceptions and error control when stopping spark context and actors.
@Gschiavon 
All passed.
> [SPARKTA-197] [DRIVER] Stop policies correctly

- testsAT/README.md
- testsAT/pom.xml
- testsAT/src/test/java/com/stratio/sparkta/testsAT/automated/endtoend/ISocketOElasticsearch.java
- testsAT/src/test/resources/features/automated/endtoend/iSocketoCassandra.feature
- testsAT/src/test/resources/features/automated/endtoend/iSocketoElasticsearch.feature
- testsAT/src/test/resources/schemas/policies/iSocketoElasticsearch.conf
- testsAT/src/test/resources/schemas/policies/iSocketoMongoDB.conf
- testsAT/src/test/resources/schemas/queries/elasticsearch.conf
Migrate existing test AT to cucumber to be executed in jenkins workflow.
> [SPARKTA-244] migrate elasticsearch test AT

- plugins/parser-ingestion/src/main/scala/com/stratio/sparkta/plugin/parser/ingestion/IngestionParser.scala
Ingestion Parser has a bug when data comes from Kafka.
> [Bugfix] ingestion parser

- plugins/output-kafka/src/main/scala/com/stratio/sparkta/plugin/output/kafka/KafkaOutput.scala
- plugins/output-kafka/src/main/scala/com/stratio/sparkta/plugin/output/kafka/KafkaOutputFormat.scala
- plugins/output-kafka/src/main/scala/com/stratio/sparkta/plugin/output/kafka/producer/KafkaProducer.scala
- plugins/output-kafka/src/test/scala/KafkaProducerTest.scala
The data saved into Kafka is formatted with json or row with separator.
All OK
> [SPARKTA-256] [PLUGINS] Kafka data Formats

- plugins/output-jdbc/pom.xml
- plugins/output-jdbc/src/main/scala/com/stratio/sparkta/plugin/output/jdbc/JdbcOutput.scala
- plugins/pom.xml
- web/src/data-templates/output.json
- web/src/languages/en-US.json
New output for save the aggregated data into SQL Database with JDBC connector.
Is mandatory define properties like:
"url"="jdbc:mysql://localhost:3306/hadoopdb"
Optionals:
"driver" = ...
"user" = ...
"password" = ...
All passed.
> [SPARKTA-337] JDBC Output

- testsAT/src/test/java/com/stratio/sparkta/testsAT/automated/gui/outputs/AddNewJDBC.java
- testsAT/src/test/java/com/stratio/sparkta/testsAT/automated/gui/outputs/AddNewKafka.java
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputKafka.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputJDBC.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputKafka.feature
Add new acceptance tests for the new outputs created
> [SPARKTA-376] new acceptance tests fro Kafka and JDBC outputs

- driver/pom.xml
- driver/src/main/scala/com/stratio/sparkta/driver/SparktaClusterJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/SparktaJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/service/StreamingContextService.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/SparktaJobTest.scala
- sdk/src/main/scala/com/stratio/sparkta/sdk/Parser.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/ClusterLauncherActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/LocalSparkStreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/SparkStreamingContextActor.scala
- serving-api/src/main/scala/com/stratio/sparkta/serving/api/helpers/SparktaHelper.scala
- serving-core/pom.xml
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/CuratorFactoryHolder.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/SparktaConfig.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/constants/AppConstant.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/constants/Error.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/dao/ConfigDAO.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/dao/ErrorDAO.scala
This PR follows #1379. Now, the errors are stored in ZK.
SPARKTA-335
@danielcsant   
All OK
> [SPARKTA-335] Errors stored in ZK

- plugins/field-geoHash/src/main/scala/com/stratio/sparkta/plugin/field/geohash/GeoHashField.scala
- plugins/field-geoHash/src/test/scala/com/stratio/sparkta/plugin/field/geohash/GeoHashFieldTest.scala
- plugins/parser-ingestion/src/main/scala/com/stratio/sparkta/plugin/parser/ingestion/IngestionParser.scala
Refactor of the GeoHashField class.
-> [Ticket in JIRA](https://stratio.atlassian.net/browse/SPARKTA-362)
Previous PR: #1412
> SPARKTA-362 Refactor in GeoHashField

- plugins/parser-geo/src/main/scala/com/stratio/sparkta/plugin/parser/geo/GeoParser.scala
- plugins/parser-ingestion/src/main/scala/com/stratio/sparkta/plugin/parser/ingestion/IngestionParser.scala
Fixed some problems about GeoParser and IngestionParser.
Now, they work properly.
It would be necessary check the rest of parsers in other task.
> SPARKTA-433 Fixed bugs in geo parser and ingestion parser

- driver/src/main/scala/com/stratio/sparkta/driver/SparktaJob.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/models/AggregationPoliciesTest.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/helpers/OperationsHelper.scala
- serving-core/src/main/scala/com/stratio/sparkta/serving/core/models/AggregationPoliciesModel.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/helpers/OperationsHelperTest.scala
- serving-core/src/test/scala/com/stratio/sparkta/serving/core/helpers/PolicyHelperTest.scala
Doc updated: https://stratio.atlassian.net/wiki/display/SPARKTA/4.+Get+Started
> [SPARKTA-431] Spark Streaming window refactor

- serving-api/src/main/scala/com/stratio/sparkta/serving/api/actor/PolicyActor.scala
There were an error saving an edited policy
> [SPARKTA-460] Error with absolute path in checkpoint

- web/src/data-templates/policy.json
- web/src/languages/en-US.json
- web/src/scripts/controllers/policies/policy-cube.js
- web/src/scripts/controllers/policies/policy-model-accordion.js
- web/src/scripts/controllers/policies/policy-model.js
- web/src/scripts/controllers/policies/trigger.js
- web/src/scripts/directives/c-accordion-directive.js
- web/src/scripts/directives/c-add-element-directive.js
- web/src/scripts/services/model-service.js
- web/src/scripts/services/trigger-service.js
- web/src/stratio-ui/script/directives/forms/form-field-textarea-directive.js
- web/src/stratio-ui/template/form/form_field_textarea.html
- web/src/styles/custom/angular-ui/components/c-accordion/_rules.scss
- web/src/styles/sparkta-ui/components/c-cube/_rules.scss
- web/src/styles/sparkta-ui/components/c-form-group/_rules.scss
- web/src/styles/sparkta-ui/components/c-info-text/_rules.scss
- web/src/styles/sparkta-ui/components/c-info-text/_vars.scss
- web/src/styles/sparkta-ui/components/c-panel/_rules.scss
- web/src/styles/sparkta-ui/components/c-step-content/_rules.scss
- web/src/styles/sparkta-ui/components/c-textarea/_rules.scss
- web/src/templates/components/c-add-element.tpl.html
- web/src/templates/policies/transformation/datetime-panel.tpl.html
- web/src/templates/policies/transformation/ingestion-panel.tpl.html
- web/src/templates/policies/transformation/morphlines-panel.tpl.html
- web/src/views/policy-wizard/cube-panel.html
- web/src/views/policy-wizard/transformation-step-content.html
- web/src/views/policy-wizard/trigger-accordion.html
- web/src/views/policy-wizard/trigger-panel.html
fix: trigers design 1/2
fix: triggers layout
fix: transformation morphline commands
fix: triggers design
fix: c-add-elements directive width
fix: triggering validations
fix: transformation validations
> fix: delete transformation modal size

- aggregator/src/main/scala/com/stratio/sparkta/aggregator/Cube.scala
- aggregator/src/main/scala/com/stratio/sparkta/aggregator/CubeMaker.scala
- aggregator/src/test/scala/com/stratio/sparkta/aggregator/CubeMakerTest.scala
- aggregator/src/test/scala/com/stratio/sparkta/aggregator/CubeTest.scala
Avoid Spark shuffle with mapPartitions and removing filter with map.
> [SPARKTA-449] Improve performance in cube and cubemaker

- driver/src/main/scala/com/stratio/sparkta/driver/SparktaJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/helper/SchemaHelper.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/helper/SchemaHelperTest.scala
- plugins/src/main/scala/com/stratio/sparkta/plugin/parser/geo/GeoParser.scala
- Fixed bug about order
- Fixed bug about schemas and attachment field
> SPARKTA-463 Fix bug about order and attachment field

- web/src/data-templates/output.json
- web/src/data-templates/policy.json
- web/src/scripts/controllers/policies.js
- web/src/styles/sparkta-ui/components/c-msg/_rules.scss
- web/src/styles/sparkta-ui/components/c-msg/_vars.scss
- web/src/styles/sparkta-ui/components/c-table/_rules.scss
- web/src/views/inputs.html
- web/src/views/outputs.html
- web/src/views/policies.html
fix: policy list dropdown menu
> fix: error messages animations

- plugins/pom.xml
Platform epic: https://stratio.atlassian.net/browse/PLATFORM-88
> [SPARKTA-462] Updated Cassandra connector

- web/src/data-templates/policy.json
- web/src/languages/en-US.json
- web/src/scripts/controllers/policies.js
- web/src/scripts/controllers/policies/edit-policy.js
- web/src/scripts/controllers/policies/modal/policy-creation-modal.js
- web/src/scripts/controllers/policies/new-policy.js
- web/src/scripts/controllers/policies/policy-wizard-header.js
- web/src/templates/modal/confirm-modal.tpl.html
- web/src/templates/modal/policy-creation-modal.tpl.html
- web/src/views/dashboard/dashboard_header.html
- web/src/views/policy-wizard/cube-panel.html
- web/src/views/policy-wizard/cube-step-content.html
- web/src/views/policy-wizard/header.html
- web/src/views/policy-wizard/input.html
- web/src/views/policy-wizard/wizard-panel.html
- web/test/mock/policyTemplate.json
- web/test/policies/policy-creation-modal-spec.js
- web/test/policies/wizard/controller/policy-wizard-header-controller.js
fix: finish view
fix: delete help messages, fix policy error messages, add exit editor modal
> fix: add output properties

- driver/src/main/scala/com/stratio/sparkta/driver/SparktaJob.scala
- driver/src/main/scala/com/stratio/sparkta/driver/helper/SchemaHelper.scala
- driver/src/test/scala/com/stratio/sparkta/driver/test/helper/SchemaHelperTest.scala
- plugins/src/main/scala/com/stratio/sparkta/plugin/field/geohash/GeoHashField.scala
- plugins/src/main/scala/com/stratio/sparkta/plugin/parser/geo/GeoParser.scala
- plugins/src/main/scala/com/stratio/sparkta/plugin/parser/ingestion/IngestionParser.scala
- plugins/src/test/scala/com/stratio/sparkta/plugin/test/field/geohash/GeoHashFieldTest.scala
- plugins/src/test/scala/com/stratio/sparkta/plugin/test/parser/geo/GeoParserTest.scala
- pom.xml
- Fixed demo with orders
- Added new Geo Parser
[Ticket in JIRA](https://stratio.atlassian.net/browse/SPARKTA-431)
> Sparkta 431 fix demo policy

- testsAT/src/test/resources/features/automated/gui/policies/runPolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/stopPolicy.feature
fix stop and run policy testsAT
> fix testsAT for gui policies

- CHANGELOG.md
Necessary to make the release.
Pending to add documentation of some features
> [SPARKTA-466] Updated changelog

- web/src/scripts/controllers/policies/policy-finish.js
- web/src/scripts/factories/policy-model-factory.js
- web/test/policies/wizard/factory/policy-model-factory.js
* Remove unused attributes from final json generated by wizard
* Formatted sparkStreamingWindow attribute to the agreed format
> [SPARKTA-420][WEB]: Fix bugs to json generated by policy wizard

- examples/policies/Twitter-Triggers-MongoDb-Kafka.json
- examples/policies/Twitter-Triggers-MongoDb.json
***given*** an instance of Sparta
***when*** you want to make one policy with triggers and outputs from Twitter
***then*** you have examples for this use case
> [SPARKTA-486] [EXAMPLES] Advanced Twitter policies with triggers and multiple outputs

- Docker/README.md
- Docker/docker-entrypoint.sh
- Docker/sparta-compose.yml
- dist/pom.xml
- dist/src/main/unix/files/DEBIAN/conffiles
Update unix-maven-plugin and follow modules dockerization guidelines
> [SPARKTA-503] [SPARKTA-504] unix and docker update

- web/src/index.html
- web/src/languages/en-US.json
- web/src/scripts/app.js
- web/src/scripts/factories/request-interceptor-factory.js
- web/src/scripts/services/api/api-policy-service.js
- web/src/styles/sparkta-ui/components/c-msg/_rules.scss
- web/src/styles/sparkta-ui/components/c-msg/_vars.scss
- web/src/views/dashboard/dashboard_content.html
- web/test/factories/request-interceptor-factory.js
When Zookeeper is not available, the Web Interface has to show an error.
> [SPARKTA-494][WEB]: Manage unavailable server error

- web/src/data-templates/policy.json
- web/src/scripts/controllers/policies/policy-finish.js
- web/src/scripts/controllers/policies/trigger.js
- web/src/scripts/factories/trigger-model-factory.js
- web/src/scripts/services/trigger-service.js
- web/test/mock/policyTemplate.json
- web/test/policies/wizard/controller/trigger-controller.js
- web/test/policies/wizard/factory/trigger-model-factory.js
- web/test/policies/wizard/service/TRIGGER-service.js
OverLast attribute has been removed from cube triggers.
OverLast attribute is still configured to transformation triggers.
> [SPARKTA-506][WEB]: Remove overLast attribute from cube triggers

- serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/ClusterLauncherActor.scala
Fixed bug with Java 7.
Method waitFor(timeout, timeformat) is not available in Java 7 (only for Java 8).
I've used the method waitFor() without timeout ([Documentation here](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor--))
[Ticket in Jira](https://stratio.atlassian.net/browse/SPARKTA-415)
- Using Java 7 Spark should be launched properly in cluster mode
- Using Java 8 Spark should be launched properly in cluster mode
> SPARKTA-415 Fixed bug with Java 7 in waitFor method

- web/src/scripts/controllers/inputs.js
- web/src/scripts/controllers/outputs.js
- web/src/templates/modal/confirm-modal.tpl.html
- web/src/templates/policies/st-delete-policy-modal.tpl.html
- web/test/inputs/inputs-controller.js
Fix error showing confirmation text
> [SPARTA-527][WEB]: Fix confirmation text

- testsAT/src/test/resources/features/automated/gui/policies/addNewPolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/editPolicy.feature
fix testsAT for latest qa labels and add test for geo parser
> fix testsAT for geo and new qa labels

- serving-api/src/main/scala/com/stratio/sparta/serving/api/actor/PolicyActor.scala
- serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/FragmentHttpService.scala
- serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyHttpService.scala
- serving-api/src/main/scala/com/stratio/sparta/serving/api/utils/PolicyUtils.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/FragmentHttpServiceTest.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/HttpServiceBaseTest.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/utils/BaseUtilsTest.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/utils/PolicyUtilsTest.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/utils/SparkStreamingContextUtilsTest.scala
**Given** an existing policy which contains some fragments
**When** you modify any of these fragments
**Then** the checkpoint associated with this policy must be deleted
> [SPARTA-508] add delete checkpoints when updating fragments

- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputKafka.feature
With the addition of the checkbox instead of an input field for kafka acks, testsAT need to be changed
> [SPARTA-539] update testsAT for kafka output

- driver/src/main/scala/com/stratio/sparta/driver/SpartaJob.scala
- driver/src/main/scala/com/stratio/sparta/driver/service/RawDataStorageService.scala
**given** a running Sparta policy which writes raw data in HDFS
**when** you stop and run again the policy (there is already checkpoint created)
**then** verify no NullPointerException is thrown
> [SPARTA-523] error persisting raw data in HDFS

- serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyContextHttpService.scala
- serving-api/src/main/scala/com/stratio/sparta/serving/api/service/http/PolicyHttpService.scala
- serving-api/src/main/scala/com/stratio/sparta/serving/api/utils/PolicyStatusUtils.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/PolicyContextHttpServiceTest.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/service/http/PolicyHttpServiceTest.scala
- serving-api/src/test/scala/com/stratio/sparta/serving/api/utils/PolicyStatusUtilsTest.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/constants/AppConstant.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/helpers/ResourceManagerLink.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/PoliciesStatusModel.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/policy/status/PolicyStatusActor.scala
- serving-core/src/test/scala/com/stratio/sparta/serving/core/helpers/ResourceManagerLinkIT.scala
- test-at/pom.xml
- web/src/languages/en-US.json
- web/src/scripts/controllers/policies.js
- web/src/scripts/services/api/api-policy-service.js
- web/src/styles/custom/stratio-ui/components/br-ba-container/_rules.scss
- web/src/styles/custom/stratio-ui/components/br-ba-container/_vars.scss
- web/src/styles/sparkta-ui/components/c-msg/_rules.scss
- web/src/styles/sparkta-ui/components/c-table/_rules.scss
- web/src/styles/sparkta-ui/components/c-table/_vars.scss
- web/src/views/policies.html
- web/test/mock/policiesStatusList.json
**Given** Sparta running in local with the default port 4040
**When** a policy is running 
**Then** a link should be shown to the SPARK UI
**Given** Sparta running aggainst Mesos with the default port 5050
**When** listing the policies
**Then** a link should be shown to the Mesos UI
**Given** Sparta running aggainst YARN with the default port 8088
**When** listing the policies
**Then** a link should be shown to the YARN UI
**Given** Sparta running aggainst Spark Standalone with the default port 8080
**When** listing the policies
**Then** a link should be shown to the Spark Standalone UI
> [SPARTA-295] check error logs from ui

- Docker/sparta-compose-cassandra.yml
modify compose file and create new one with cassandra
> modify compose file and create new one with cassandra

- web/src/scripts/controllers/policies/policy-cube.js
- web/src/scripts/factories/cube-model-factory.js
- web/src/scripts/services/cube-service.js
- web/src/scripts/services/policy-service.js
- web/src/scripts/services/utils-service.js
- web/src/views/policy-wizard/cube-panel.html
- web/test/mock/model/cube.json
- web/test/policies/wizard/controller/policy-cube-controller.js
- web/test/policies/wizard/factory/cube-model-factory.js
- web/test/policies/wizard/factory/policy-model-factory.js
- web/test/policies/wizard/service/TRIGGER-service.js
Fixed cube edition in order to be able to change values to attributes:
- Fixed measure
- isAutoCalculatedId
- dateType
> [SPARTA-541][WEB]: Fix error editing policy

- testsAT/src/test/resources/features/automated/gui/policies/addNewPolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/editPolicy.feature
fis tests after latest changes
> fix testsAT addNewPolicy and editPolicy from gui

- web/src/scripts/controllers/policies/modal/new-operator-modal.js
- web/src/scripts/controllers/policies/policy-cube.js
- web/src/scripts/controllers/policies/policy.js
- web/src/scripts/services/utils-service.js
- web/src/templates/policies/operator-modal.tpl.html
- web/test/policies/wizard/controller/new-operator-modal-controller.js
- web/test/policies/wizard/controller/policy-controller.js
- web/test/service/accordion-status-service.js
- web/test/service/modal-service.js
- web/test/service/utils-service.js
Allow user to select an input field through a select when he is creating a cube operator
> [SPARTA-554][WEB]: Add select to change the input field in operator modal

- testsAT/src/test/resources/features/automated/api/policies/postPolicies.feature
- testsAT/src/test/resources/features/automated/api/policies/putPolicies.feature
- testsAT/src/test/resources/features/automated/api/policyContexts/postPolicyContexts.feature
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputFlume.feature
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputKafka.feature
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputKafkaDirect.feature
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputRabbitMQ.feature
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputSocket.feature
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputTwitter.feature
- testsAT/src/test/resources/features/automated/gui/inputs/addNewInputWebSocket.feature
- testsAT/src/test/resources/features/automated/gui/inputs/duplicateInput.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputCSV.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputCassandra.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputElasticSearch.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputJDBC.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputKafka.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputMongoDB.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputParquet.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputPrint.feature
- testsAT/src/test/resources/features/automated/gui/outputs/addNewOutputRedis.feature
- testsAT/src/test/resources/features/automated/gui/outputs/duplicateOutput.feature
- testsAT/src/test/resources/features/automated/gui/policies/addNewPolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/deletePolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/runPolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/stopPolicy.feature
after changes for policies with no cubes, error messages have changed
> fix testsAT for new messages added for policies with no cubes

- web/src/scripts/controllers/policies/policy-cube.js
- web/src/views/policy-wizard/cube-panel.html
- web/src/views/policy-wizard/trigger-panel.html
- web/src/views/policy-wizard/wizard-panel.html
- web/test/policies/wizard/controller/policy-cube-controller.js
Given the policy wizard
When I am creating a cube
And I dont add an outout nor a trigger
Then error is displayed in cube output
Given the policy wizard
When I am creating a cube
And I add a  trigger but not an output to cube
Then policy is succesfully created
Given the policy wizard
When I am creating a cube
And I add an output to cube
Then policy is succesfully created
> [SPARTA-557][WEB]: As a user I want to be told when I am creating a cube without any outputs

- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/AggregationPoliciesModel.scala
As an user I want to validate that a policy has at least:
- One valid output
or
- One trigger that has a valid output.
> [SPARTA-557] The policy needs at least one output or one trigger in the cube with output

- web/src/data-templates/policy.json
- web/src/scripts/controllers/policies/policy-cube.js
- web/src/scripts/directives/c-accordion-directive.js
- web/src/scripts/factories/cube-model-factory.js
- web/src/scripts/services/cube-service.js
- web/src/scripts/services/trigger-service.js
- web/src/views/policy-wizard/cube-panel.html
- web/test/policies/wizard/service/TRIGGER-service.js
- web/test/policies/wizard/service/policy-cube-service.js
**Given** a policy wizard
**When** I am creating a cube and I remove all their outputs
**Then** output field is shown in red
> [SPARTA-557][WEB]: Fix bug when user removes all outputs of cube

- testsAT/src/test/resources/features/automated/gui/policies/addNewPolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/editPolicy.feature
after making output compulsory for triggers tests need to be changed and after adding a new operator for associative mean
> fix testsAT for compulsory output in triggers

- CHANGELOG.md
Changed release date
- Addition of a new operator: Associative Mean
- Fixes for Count and Sum operators
- Added flexibility to create policies with no cubes
- Integration with a SSO
- Sparta API supports SSL
> Update changelog with latest changes

- CHANGELOG.md
- driver/src/main/scala/com/stratio/sparta/driver/util/HdfsUtils.scala
> conf from hadoop xml files

- web/src/languages/en-US.json
- web/src/scripts/controllers/policies/policy-cube.js
- web/src/scripts/controllers/policies/policy-model-accordion.js
- web/src/scripts/controllers/policies/policy.js
- web/src/scripts/controllers/policies/trigger.js
- web/src/scripts/directives/c-accordion-directive.js
- web/src/scripts/factories/cube-model-factory.js
- web/src/scripts/factories/policy-model-factory.js
- web/src/scripts/factories/trigger-model-factory.js
- web/src/scripts/services/trigger-service.js
- web/src/views/policy-wizard/cube-panel.html
- web/src/views/policy-wizard/trigger-accordion.html
- web/src/views/policy-wizard/trigger-panel.html
- web/test/directive/c-accordion-directive.js
- web/test/policies/wizard/controller/policy-controller.js
- web/test/policies/wizard/controller/trigger-controller.js
- web/test/policies/wizard/factory/policy-model-factory.js
- web/test/policies/wizard/factory/trigger-model-factory.js
- web/test/policies/wizard/service/TRIGGER-service.js
*Given* a policy wizard 
*When* I am creating a stream trigger
*And* I add an overlast which is not multiple of policy batch window
*Then* error is shown
*Given* a policy wizard 
*When* I edit the policy batch window
*And* policy has stream triggers
*And* I click on the 'save policy' button
*Then* Error is shown telling me that overlast has to be multiple of policy batch window
**NOTE:** Bug in trigger accordion has been fixed. When user was creating a trigger and he changed to see a previous created trigger and he came back to the trigger creation, view was not updated correctly.
> [SPARTA-568][WEB]: Over Last in Streams Triggers must be a multiple of Batch window

- testsAT/src/test/resources/features/automated/gui/inputs/deleteInputChained.feature
- testsAT/src/test/resources/features/automated/gui/outputs/deleteOutputChained.feature
[SPARTA-591] fix testsAT after changes in english messages
> [SPARTA-591] fix testsAT after changes in english messages

- testsAT/src/test/java/com/stratio/tests/utils/CukesHooks.java
- testsAT/src/test/resources/features/automated/gui/policies/addNewPolicy.feature
- testsAT/src/test/resources/features/automated/gui/policies/editPolicy.feature
> [SPARTA-589] fix testsAT add and edit policy

- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/AggregationPoliciesModel.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/ErrorModel.scala
As an user I want to validate that the overlast number should be  a multiple of the spark window.
> [SPARTA-569] Overlast backend validation

- web/src/scripts/controllers/policy-list.js
**Given** the policy list openend at Firefox browser
**When** I click to download a policy
**Then** policy is downloaded succesfully
> [SPARTA-652][WEB]:Fix policy download in Firefox

- plugins/pom.xml
- plugins/src/main/scala/com/stratio/sparta/plugin/input/kafka/KafkaDirectInput.scala
- plugins/src/main/scala/com/stratio/sparta/plugin/input/kafka/KafkaInput.scala
- plugins/src/main/scala/com/stratio/sparta/plugin/parser/ingestion/IngestionParser.scala
- plugins/src/main/scala/com/stratio/sparta/plugin/parser/ingestion/serializer/JavaToAvroSerializer.java
- plugins/src/main/scala/com/stratio/sparta/plugin/parser/ingestion/serializer/Serializer.java
- plugins/src/test/scala/com/stratio/sparta/plugin/parser/ingestion/IngestionParserTest.scala
Due to Avro serialization in Decision it is neccesary this upgrade
**Given** this doc https://docs.google.com/document/d/1VaYMMw30GT1me6T15qfjpsQOs8TYMcpB5r7GV8_L2p8/edit
**When** following Ingestion, Decision and Sparta steps
**Then** data should be written in Cassandra in keyspace shoppingcentertest
> [SPARTA-648] Ingestion parser is not working

- driver/src/main/scala/com/stratio/sparta/driver/SpartaJob.scala
- driver/src/main/scala/com/stratio/sparta/driver/trigger/StreamWriter.scala
- driver/src/main/scala/com/stratio/sparta/driver/trigger/Trigger.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/AggregationPoliciesModel.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/ErrorModel.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/TriggerModel.scala
- web/src/data-templates/policy.json
- web/src/languages/en-US.json
- web/src/scripts/factories/policy-model-factory.js
- web/src/scripts/factories/trigger-model-factory.js
- web/src/scripts/services/policy-service.js
- web/test/mock/api/cube.json
- web/test/mock/api/policy.json
- web/test/mock/api/trigger.json
- web/test/mock/model/policy.json
- web/test/mock/model/trigger.json
- web/test/mock/template/policy.json
- web/test/policies/wizard/factory/policy-model-factory.js
- web/test/policies/wizard/factory/trigger-model-factory.js
- web/test/policies/wizard/service/policy-service.js
**Given** a policy with one stream trigger
**When** I add the slidding window
**Then** the policy should run and check the correct value of the spark streaming window property
> [SPARTA-600] [DRIVER] [SERVING-API] [WEB] Slide window added to stream triggers

- web/pom.xml
move nodeURL to node profile, to avoid usage of internal repo when needed  Fixes #1589
> Unknown host tools.stratio.com: unknown error

- dist/src/main/resources/application.conf
- docker/README.md
- docker/docker-entrypoint.sh
- driver/src/main/scala/com/stratio/sparta/driver/util/HdfsUtils.scala
Sparta's Kerberos Integration.
Now the config has two new variables:
- principalName
- keytabPath
> HdfsUtils using kerberos

- driver/src/main/scala/com/stratio/sparta/driver/SpartaPipeline.scala
- driver/src/main/scala/com/stratio/sparta/driver/helper/SchemaHelper.scala
- driver/src/main/scala/com/stratio/sparta/driver/writer/StreamWriter.scala
- driver/src/main/scala/com/stratio/sparta/driver/writer/TriggerWriter.scala
- pom.xml
- serving-core/src/main/scala/com/stratio/sparta/serving/core/models/policy/PolicyModel.scala
- serving-core/src/main/scala/com/stratio/sparta/serving/core/utils/PolicyStatusUtils.scala
- web/src/data-templates/policy.json
- web/src/languages/en-US.json
- web/src/scripts/factories/policy-model-factory.js
Added validators in streamWriter when drop/register temporal tables in spark
> Stream trigger with optional temporal table name 

- driver/src/main/scala/com/stratio/sparta/driver/service/StreamingContextService.scala
- plugins/src/main/scala/com/stratio/sparta/plugin/output/jdbc/JdbcOutput.scala
- serving-api/src/main/scala/com/stratio/sparta/serving/api/utils/SparkSubmitUtils.scala
Added custom properties to connection properties in jdbc
> Add plugins files to driver and executor classpath

- web/src/data-templates/policy.json
> [SPARTA-791]  Fix documentation links

- docker/sparta-common.sh
- driver/pom.xml
- plugins/pom.xml
- pom.xml
* Added Zookeeper exclusion to some of the pom.xml inside the project
* Removed some defaults Zookeeper jars in docker image
* Updated Curator version
* Added HTTP components dependencies
> Updated Curator, added Zookeeper exclusions in maven
